#!/usr/bin/env bash
# clean_repo.sh — Tidy up TensorLBM root directory.
#
# 1. Moves benchmark run artifacts (*.json, *.log, *.npy, log_*.txt) to
#    artifacts/runs/ so they stop polluting the project root.
# 2. Moves ad-hoc _* debug/benchmark Python scripts to
#    experiments/archived/.
# 3. Removes the tracking of all those files from the git index
#    (git rm --cached) so they are no longer committed.
# 4. Appends the corresponding glob patterns to .gitignore so future
#    benchmark runs are automatically ignored.
#
# Usage:
#   bash clean_repo.sh          # dry-run (shows what would happen)
#   bash clean_repo.sh --apply  # actually move / git-rm / update .gitignore
#
# Note: the script must be run from the repository root.

set -euo pipefail

DRY_RUN=true
if [[ "${1:-}" == "--apply" ]]; then
    DRY_RUN=false
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# ── helpers ─────────────────────────────────────────────────────────────────

run() {
    if $DRY_RUN; then
        echo "[DRY-RUN] $*"
    else
        echo "+ $*"
        "$@"
    fi
}

move_file() {
    local src="$1" dst_dir="$2"
    if $DRY_RUN; then
        echo "[DRY-RUN] mv $src -> $dst_dir/"
    else
        mkdir -p "$dst_dir"
        mv "$src" "$dst_dir/"
        echo "  moved: $src -> $dst_dir/"
    fi
}

# ── 1. Artifact directories ─────────────────────────────────────────────────

ARTIFACTS_DIR="artifacts/runs"
echo ""
echo "=== Step 1: Moving benchmark run artifacts to $ARTIFACTS_DIR/ ==="

# Root-level *.json files (benchmark results, NOT pyproject.toml)
for f in *.json; do
    [[ "$f" == "pyproject.toml" ]] && continue
    [[ -f "$f" ]] && move_file "$f" "$ARTIFACTS_DIR"
done

# Root-level *.log files
for f in *.log; do
    [[ -f "$f" ]] && move_file "$f" "$ARTIFACTS_DIR"
done

# Root-level *.npy files
for f in *.npy; do
    [[ -f "$f" ]] && move_file "$f" "$ARTIFACTS_DIR"
done

# Root-level log_*.txt files
for f in log_*.txt; do
    [[ -f "$f" ]] && move_file "$f" "$ARTIFACTS_DIR"
done

# ── 2. Ad-hoc worker / debug scripts ────────────────────────────────────────

ARCHIVED_DIR="experiments/archived"
echo ""
echo "=== Step 2: Moving _* debug/benchmark scripts to $ARCHIVED_DIR/ ==="

for f in _*.py; do
    [[ -f "$f" ]] && move_file "$f" "$ARCHIVED_DIR"
done

# Root-level ad-hoc test scripts (keep canonical tests under tests/)
for f in test_*.py; do
    [[ -f "$f" ]] && move_file "$f" "$ARCHIVED_DIR"
done

# ── 3. git rm --cached for all moved files ───────────────────────────────────

echo ""
echo "=== Step 3: Removing moved files from git index ==="

if $DRY_RUN; then
    echo "[DRY-RUN] Would run: git rm --cached <all moved files>"
else
    # Gather paths that git is currently tracking in repository root only.
    # (Avoid touching similarly named files in sub-directories.)
    git ls-files | grep -E '^[^/]+\.json$' | xargs -r git rm --cached --quiet || true
    git ls-files | grep -E '^[^/]+\.log$' | xargs -r git rm --cached --quiet || true
    git ls-files | grep -E '^[^/]+\.npy$' | xargs -r git rm --cached --quiet || true
    git ls-files | grep -E '^[^/]+$' | grep -E '^log_.*\.txt$' | xargs -r git rm --cached --quiet || true
    git ls-files | grep -E '^[^/]+$' | grep -E '^_.*\.py$' | xargs -r git rm --cached --quiet || true
    git ls-files | grep -E '^[^/]+$' | grep -E '^test_.*\.py$' | xargs -r git rm --cached --quiet || true
    echo "  Done — run 'git status' to review."
fi

# ── 4. Update .gitignore ─────────────────────────────────────────────────────

echo ""
echo "=== Step 4: Updating .gitignore ==="

GITIGNORE=".gitignore"

BLOCK=$(cat <<'EOF'

# ── Benchmark run artifacts (generated by benchmark scripts) ────────────────
# Root-level result files
/*.json
/*.log
/*.npy
/log_*.txt

# Archived experiment scripts
/_*.py
/test_*.py

# artifacts/ directory (all benchmark outputs)
artifacts/runs/
EOF
)

if $DRY_RUN; then
    echo "[DRY-RUN] Would append to $GITIGNORE:"
    echo "$BLOCK"
else
    # Only append if the block is not already present
    if ! grep -qF "Benchmark run artifacts" "$GITIGNORE" 2>/dev/null; then
        echo "$BLOCK" >> "$GITIGNORE"
        echo "  .gitignore updated."
    else
        echo "  .gitignore already contains the artifact patterns — skipped."
    fi
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
if $DRY_RUN; then
    echo "=== Dry-run complete. Re-run with --apply to make changes. ==="
else
    echo "=== Done. Next steps: ==="
    echo "  git add .gitignore artifacts/ experiments/"
    echo "  git commit -m 'chore(cleanup): move root artifacts and worker scripts'"
fi
