"""Physics/collision namespace for grouped imports."""
from __future__ import annotations

from ..multiphase import (
    collide_sc_single_component,
    collide_sc_two_component,
    color_gradient_step,
    free_energy_step,
    init_free_energy_g,
    psi_exp,
    psi_linear,
    psi_power,
    sc_single_component_force,
    sc_two_component_force,
)
from ..multiphase3d import (
    collide_sc_single_component_3d,
    collide_sc_two_component_3d,
    color_gradient_step_3d,
    free_energy_step_3d,
    init_free_energy_g_3d,
    sc_two_component_force_3d,
)
from ..solver import collide_bgk, collide_mrt, collide_rlbm, collide_trt, correct_mass, stream
from ..solver3d import (
    collide_bgk3d,
    collide_mrt3d,
    collide_rlbm3d,
    collide_trt3d,
    correct_mass3d,
    stream3d,
)
from ..thermal import (
    C_D2Q5,
    W_D2Q5,
    apply_buoyancy_force,
    collide_thermal_bgk,
    equilibrium_thermal,
    macroscopic_thermal,
    stream_thermal,
)
from ..thermal3d import (
    C_D3Q7,
    W_D3Q7,
    apply_buoyancy_force_3d,
    collide_thermal_bgk_3d,
    equilibrium_thermal_3d,
    macroscopic_thermal_3d,
    stream_thermal_3d,
)
from ..turbulence import (
    collide_dynamic_smagorinsky_bgk,
    collide_dynamic_smagorinsky_bgk3d,
    collide_smagorinsky_bgk,
    collide_smagorinsky_bgk3d,
    collide_smagorinsky_bgk27,
    collide_smagorinsky_mrt,
    collide_smagorinsky_mrt3d,
    collide_smagorinsky_mrt27,
)

__all__ = [
    "collide_bgk",
    "collide_mrt",
    "collide_rlbm",
    "collide_trt",
    "stream",
    "correct_mass",
    "collide_bgk3d",
    "collide_mrt3d",
    "collide_rlbm3d",
    "collide_trt3d",
    "stream3d",
    "correct_mass3d",
    "psi_linear",
    "psi_exp",
    "psi_power",
    "sc_two_component_force",
    "collide_sc_two_component",
    "sc_single_component_force",
    "collide_sc_single_component",
    "color_gradient_step",
    "free_energy_step",
    "init_free_energy_g",
    "sc_two_component_force_3d",
    "collide_sc_two_component_3d",
    "collide_sc_single_component_3d",
    "color_gradient_step_3d",
    "init_free_energy_g_3d",
    "free_energy_step_3d",
    "collide_smagorinsky_bgk",
    "collide_smagorinsky_mrt",
    "collide_smagorinsky_bgk3d",
    "collide_smagorinsky_mrt3d",
    "collide_smagorinsky_bgk27",
    "collide_smagorinsky_mrt27",
    "collide_dynamic_smagorinsky_bgk",
    "collide_dynamic_smagorinsky_bgk3d",
    "C_D2Q5",
    "W_D2Q5",
    "equilibrium_thermal",
    "collide_thermal_bgk",
    "stream_thermal",
    "macroscopic_thermal",
    "apply_buoyancy_force",
    "C_D3Q7",
    "W_D3Q7",
    "equilibrium_thermal_3d",
    "collide_thermal_bgk_3d",
    "stream_thermal_3d",
    "macroscopic_thermal_3d",
    "apply_buoyancy_force_3d",
]
