#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $0 L90 PHYSICAL_GPU [RESULT_DIR] [WAIT_FOR_PID]" >&2
  exit 2
}

[[ $# -ge 2 && $# -le 4 ]] || usage
[[ $1 == L90 ]] || usage

# First three-level generation after the wall-traction source became exactly
# mass conservative.  Use this wrapper for both sides of open-boundary A/B
# studies; set TENSORLBM_SPONGE_INLET=1 and a distinct campaign generation for
# the inlet-sponge member.
export TENSORLBM_CAMPAIGN_GENERATION=${TENSORLBM_CAMPAIGN_GENERATION:-v13}
export TENSORLBM_INNER_WALL_MARGIN=${TENSORLBM_INNER_WALL_MARGIN:-8}
export TENSORLBM_INNER_WAKE_CELLS=${TENSORLBM_INNER_WAKE_CELLS:-12}
export TENSORLBM_CV_MARGIN=${TENSORLBM_CV_MARGIN:-8}
export TENSORLBM_AUX_CV_MARGINS=${TENSORLBM_AUX_CV_MARGINS:-4,12}
export TENSORLBM_STRESS_EXCHANGE_DISTANCE=${TENSORLBM_STRESS_EXCHANGE_DISTANCE:-4.21875}
export TENSORLBM_MEMORY_BYTES_PER_CELL=${TENSORLBM_MEMORY_BYTES_PER_CELL:-742}
export TENSORLBM_REGULARIZE_RESTRICTION=${TENSORLBM_REGULARIZE_RESTRICTION:-1}
export TENSORLBM_REGULARIZE_PROLONGATION=${TENSORLBM_REGULARIZE_PROLONGATION:-0}
export TENSORLBM_GHOST_INTERPOLATION=${TENSORLBM_GHOST_INTERPOLATION:-trilinear}
export TENSORLBM_ENFORCE_TRANSFER_POSITIVITY=${TENSORLBM_ENFORCE_TRANSFER_POSITIVITY:-1}
export TENSORLBM_INTERFACE_FILTER_WIDTH=${TENSORLBM_INTERFACE_FILTER_WIDTH:-0}
export TENSORLBM_INTERFACE_FILTER_STRENGTH=${TENSORLBM_INTERFACE_FILTER_STRENGTH:-0}
export TENSORLBM_COLLISION_MODEL=${TENSORLBM_COLLISION_MODEL:-natural_kbc}
export TENSORLBM_CS_SMAG=${TENSORLBM_CS_SMAG:-0}
export TENSORLBM_SPONGE_INLET=${TENSORLBM_SPONGE_INLET:-0}

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
exec "$root/scripts/run_suboff_nested_v4_continuation_level.sh" "$@"
