from ._version import __version__
from .accuracy_recommendation import (
    AccuracyRecommendation,
    ConvergenceEvidence,
    ErrorMetric,
    KPIDefinition,
    PhysicalAccuracyEvidence,
    recommend_by_physical_accuracy,
)
from .acoustics import (
    AcousticObserver,
    FWHResult,
    FWHSurface,
    compute_fwh_far_field,
    compute_fwh_result,
    compute_spl_spectrum,
    extract_surface_pressure,
    oaspl,
)
from .acoustics_capability_contract import (
    AcousticsCapability,
    AcousticsWithheldError,
    PostProcessingAudit,
    acoustics_capability_matrix,
    acoustics_post_processing_audit,
    require_acoustics_capability,
)
from .actuator_disk import (
    ActuatorDiskConfig,
    apply_actuator_disk,
    run_actuator_disk_benchmark,
)
from .adaptive_refinement import (
    MAX_VR_LEVELS,
    AdaptationSchedule,
    AdaptiveSolver2D,
    AdaptiveSolver3D,
    AMRPatch2D,
    AMRPatch3D,
    boundary_layer_indicator_2d,
    boundary_layer_indicator_3d,
    gradient_indicator_2d,
    gradient_indicator_3d,
    mark_cells_for_refinement,
    nonequilibrium_indicator_2d,
    nonequilibrium_indicator_3d,
    vorticity_indicator_2d,
    vorticity_indicator_3d,
)
from .advanced_collision_contract import (
    CollisionCapability,
    CollisionKernelWithheldError,
    collide_advanced_3d,
    collision_capability_matrix,
)
from .ai import (
    AIPipelineResult,
    EddyViscosityDataset,
    EddyViscosityMLP,
    FlowFieldTransformer,
    FlowTransformerArch,
    FlowTransformerTrainConfig,
    LBMDatabase,
    TrainConfig,
    build_flow_token_batch,
    collide_ai_les_bgk,
    extract_les_samples_2d,
    load_dataset_pt,
    load_flow_transformer_model,
    load_model,
    predict_nu_t_2d,
    predict_tau_eff_2d,
    reconstruct_flow_field,
    run_ai_dns_pipeline,
    run_ai_les_pipeline,
    save_dataset_pt,
    save_flow_transformer_model,
    save_model,
    strain_rate_tensor_2d,
    train_eddy_viscosity_model,
    train_flow_transformer_self_supervised,
)
from .airfoil_benchmark import (
    AirfoilConfig,
    build_airfoil_mask,
    naca4_surface,
    reference_cl_cd,
    run_airfoil_benchmark,
)
from .amr_capability_contract import (
    REQUIRED_FRONTEND_METADATA,
    LocalRefinementCapability,
    LocalRefinementWithheldError,
    local_refinement_capability_matrix,
    require_local_refinement_capability,
)
from .amr_interface_filter import (
    InterfaceFilterControlVolumeClearance,
    assess_interface_filter_control_volume_clearance,
    damp_interface_nonequilibrium,
    interface_shell_blend,
)
from .amr_interface_validation import (
    AMRInterfaceValidationConfig,
    run_amr_interface_validation,
)
from .backends import get_backend, set_backend
from .backward_facing_step import (
    BackwardFacingStepConfig,
    make_bfs_solid_mask,
    measure_reattachment_length,
    run_backward_facing_step,
)
from .boundaries import (
    apply_simple_channel_boundaries,
    apply_zou_he_channel_boundaries,
    bounce_back_cells,
    compute_obstacle_forces,
    cylinder_mask,
    make_channel_wall_mask,
    zou_he_inlet_velocity,
    zou_he_outlet_pressure,
)
from .boundaries3d import (
    apply_simple_channel_boundaries_3d,
    apply_water_entry_boundaries_3d,
    apply_zou_he_channel_boundaries_3d,
    bounce_back_cells_3d,
    far_field_bc_3d,
    make_channel_wall_mask_3d,
    make_tank_wall_mask_3d,
    sphere_mask,
    zou_he_inlet_velocity_3d,
    zou_he_inlet_velocity_z,
    zou_he_outlet_pressure_3d,
    zou_he_outlet_pressure_z,
)
from .boundaries_d3q27 import (
    apply_zou_he_channel_boundaries_27,
    bounce_back_cells_27,
    far_field_bc_27,
    make_channel_wall_mask_27,
    zou_he_inlet_velocity_27,
    zou_he_outlet_pressure_27,
)
from .boundary_capability_contract import (
    BoundaryConditionCapability,
    BoundaryConditionWithheldError,
    boundary_capability_matrix,
    require_boundary_condition_capability,
)
from .boundary_registry import (
    BC_ID_NONE,
    BCKind,
    BCPhase,
    BoundaryConditionRegistry,
    apply_boundary_conditions,
    boundary_condition_registry,
    build_bc_mask,
    check_bc_consistency,
    check_bc_overlaps,
    derive_missing_mask,
)

# Advanced collision common modules (cascaded central moments / entropic KBC)
from .cascaded_collision import collide_cascaded_d3q19, collide_cascaded_d3q27
from .cases import (
    CaseBase,
    CaseRunResult,
    CaseUnits,
    ExportSpec,
    get_case,
    list_cases,
    register_case,
    run_case,
)

# Cavitation common module
from .cavitation import (
    CavitationConfig,
    apply_cavitation_force,
    psi_cavitation,
    run_cavitation_flow,
    schnerr_sauer_source,
)
from .checkpoint import load_checkpoint, save_checkpoint
from .chunked_collision import (
    NaturalKBCCollisionExecutor,
    collide_in_z_chunks,
)
from .collision_viscosity_audit import (
    CollisionViscosityAuditConfig,
    run_collision_viscosity_audit,
)
from .config_io import load_config, load_config_json, load_config_yaml, save_config_json
from .conjugate_ht import (
    CHTConfig,
    CHTState,
    apply_cht_interface,
    cht_solid_diffusion_step,
    run_conjugate_ht_2d,
)
from .constants import D2Q9
from .control_volume_force import (
    ControlVolumeForceResult,
    NestedControlVolumeAssessment,
    assess_nested_control_volume_invariance,
    box_control_volume,
    fluid_momentum,
    observe_control_volume_force,
    streaming_momentum_import,
)
from .cross_module_composition_matrix import (
    CompositionDecision,
    CompositionRequest,
    CompositionStatus,
    SubContractResult,
    SubContractStatus,
    assess_composition,
)
from .cumulant import (
    collide_cumulant_d2q9,
    collide_cumulant_d3q19,
    collide_cumulant_d3q27,
    collide_cumulant_geier_d3q27,
)
from .cumulant_smag import collide_cumulant_smag_d3q27
from .cylinder_bfl_control_volume import (
    CYLINDER_RE100_CD_REFERENCE,
    CYLINDER_RE100_ST_REFERENCE,
    CylinderBFLControlVolumeConfig,
    estimate_strouhal_from_lift,
    run_cylinder_bfl_control_volume,
)
from .cylinder_flow import CylinderFlowConfig, compute_vorticity, run_cylinder_flow
from .d2q9 import OPPOSITE, C, W, equilibrium, macroscopic
from .d3q19 import OPPOSITE as OPPOSITE3D
from .d3q19 import C as C3D
from .d3q19 import W as W3D
from .d3q19 import equilibrium3d, macroscopic3d
from .d3q27 import OPPOSITE as OPPOSITE27
from .d3q27 import C as C27
from .d3q27 import W as W27
from .d3q27 import (
    collide_bgk27,
    collide_mrt27,
    collide_rlbm27,
    collide_trt27,
    correct_mass27,
    equilibrium27,
    macroscopic27,
    stream27,
    stream27_roll,
)
from .d3q27_sphere_flow import SphereFlowD3Q27Config, run_sphere_flow_d3q27
from .dam_break import DamBreakConfig, run_dam_break
from .dg_advection import (
    collide_bgk_dg,
    dg_advect,
    dg_lbm_rhs,
    dg_lbm_step,
    dg_rhs,
    equilibrium_dg,
    get_ops,
    lobatto_nodes,
    macroscopic_dg,
    nodal_from_mean,
)
from .dg_band import (
    BandTopology,
    build_band_topology,
    dg_advect_band,
    dg_lbm_step_band,
    dg_rhs_band,
    hybrid_advect,
    hybrid_step,
    write_back_exports,
)
from .dg_lbm import (
    DGLBMConfig,
    DGLBMSuboffConfig,
    build_dg_hull_band_mask,
    build_dg_shell_mask,
    collide_dg_lbm,
    dg_compute_velocity_gradients,
    run_dg_lbm_sphere_flow,
    run_dg_lbm_suboff_flow,
)
from .drag_pressure import (
    BFLWallPressureDiagnostics,
    integrate_bfl_projected_pressure,
    reconstruct_bfl_wall_pressure,
)
from .ellipsoid_benchmark import (
    EllipsoidConfig,
    build_ellipsoid_mask,
    ellipsoid_statistics,
    reference_ellipsoid_cd,
    run_ellipsoid_benchmark,
)
from .entropic_kbc import (
    collide_kbc_d3q19,
    collide_kbc_d3q27,
    collide_natural_kbc_d3q19,
    discrete_entropy,
    kbc_decompose_d3q19,
    kbc_decompose_d3q27,
    solve_gamma_entropy,
)
from .external_open_boundary import non_equilibrium_far_field_bc_3d
from .flat_plate_convergence import assess_flat_plate_convergence
from .flat_plate_wall_model import (
    FlatPlateWallModelConfig,
    ittc_1957_friction_coefficient,
    run_flat_plate_wall_model,
)

# Free-surface (VOF) common module
from .free_surface_common import (
    bubble_centroid_velocity_3d,
    free_surface_vof_collide_3d,
    free_surface_vof_step,
    gravity_force_3d,
    guo_force_delta_3d,
    init_phi_bubble_3d,
    init_phi_rayleigh_taylor_3d,
    interface_compression_3d,
    interface_normal_3d,
    mean_curvature_3d,
    mixing_layer_thickness_3d,
    surface_tension_force_3d,
    vof_advect_upwind_3d,
)
from .free_surface_lbm import (
    free_surface_step,
    init_fill_rectangular,
    init_flags_from_fill,
    init_mass_from_fill,
    total_liquid_inventory,
)
from .free_surface_lbm_2d import free_surface_step_2d, init_fill_rectangular_2d
from .free_surface_lbm_27 import (
    free_surface_step_27,
    init_fill_rectangular_27,
    init_flags_from_fill_27,
    init_mass_from_fill_27,
    total_liquid_inventory_27,
)
from .general_sim import (
    BoundaryType,
    CollisionModel,
    GeneralSimConfig,
    GeneralSimEngine,
    GeometryConfig,
    GeometrySource,
    LatticeModel,
    OutputConfig,
    OutputFormat,
    PhysicsConfig,
    SolverConfig,
)
from .hull_free_surface import HullFreeSurfaceConfig, run_hull_free_surface
from .ibm import (
    ibm_apply_body_force_2d,
    ibm_apply_body_force_3d,
    ibm_delta_4pt,
    ibm_delta_hat,
    ibm_direct_forcing,
    ibm_direct_forcing_3d,
    ibm_force_spread,
    ibm_force_spread_3d,
    ibm_velocity_interpolate,
    ibm_velocity_interpolate_3d,
)
from .inlet_profiles import (
    apply_inlet_profile_2d,
    apply_inlet_profile_3d,
    blasius_profile,
    log_law_profile,
    parabolic_profile,
    power_law_profile,
    synthetic_turbulence_2d,
    womersley_profile,
)
from .interpolated_bc import (
    bouzidi_bounce_back,
    bouzidi_bounce_back_3d,
    compute_q_circle,
    compute_q_sphere,
)
from .interpolated_bc_suboff import compute_q_suboff
from .io import save_hdf5, save_vtk, save_vtk_binary, save_vts, save_xdmf
from .lbm_step import LBMStepExecutor
from .lid_driven_cavity import (
    GHIA_RE100,
    GHIA_RE400,
    GHIA_RE1000,
    LidDrivenCavityConfig,
    compare_ghia,
    make_cavity_wall_mask,
    run_lid_driven_cavity,
    zou_he_moving_lid,
)
from .logging_config import configure_logging, logger
from .momentum_exchange import (
    compare_all_methods,
    momentum_exchange_bfl,
    momentum_exchange_galilean,
    momentum_exchange_pressure_friction,
    momentum_exchange_standard,
    momentum_exchange_stress,
)
from .multi_gpu import (
    DomainDecomposition,
    MultiDeviceSolver3D,
    MultiGPUSolver2D,
    MultiGPUSolver3D,
    auto_decompose,
    halo_exchange_2d,
    halo_exchange_3d,
)
from .multiphase import (
    collide_sc_single_component,
    collide_sc_two_component,
    color_gradient_step,
    free_energy_step,
    init_free_energy_g,
    psi_exp,
    psi_linear,
    psi_power,
    sc_single_component_force,
    sc_two_component_force,
)
from .multiphase3d import (
    collide_sc_single_component_3d,
    collide_sc_two_component_3d,
    color_gradient_step_3d,
    sc_two_component_force_3d,
)
from .multiphase3d_d3q27 import (
    collide_sc_single_component_27,
    collide_sc_two_component_27,
    free_energy_step_3d_27,
    init_free_energy_g_3d_27,
    sc_two_component_force_27,
)
from .multiphase_benchmarks import (
    FreeEnergyDropletConfig,
    MultiphaseBenchmarkSuiteConfig,
    Spinodal3DConfig,
    SpinodaleConfig,
    StaticDroplet3DConfig,
    StaticDropletConfig,
    TwoPhaseChannelCompareConfig,
    run_free_energy_droplet,
    run_multiphase_benchmark_suite,
    run_spinodal_decomposition,
    run_spinodal_decomposition_3d,
    run_static_droplet,
    run_static_droplet_3d,
    run_two_phase_channel_compare,
)
from .multiphase_water_entry import MultiphaseWaterEntryConfig, run_multiphase_water_entry
from .non_newtonian import (
    apparent_viscosity_power_law,
    collide_power_law_bgk,
    strain_rate_magnitude_2d,
)
from .obstacles import (
    compute_obstacle_forces_3d,
    compute_obstacle_forces_27,
    compute_obstacle_moments_3d,
    wigley_hull_mask,
)

# Phase-field / free-energy (Cahn-Hilliard) common module
from .phasefield import (
    DoubleWellFreeEnergy,
    FreeEnergyAdapterStreamLoopConfig,
    FreeEnergyAdapterStreamLoopResult,
    FreeEnergyCHDiagnosticResult,
    FreeEnergyCHValidationConfig,
    FreeEnergyCollisionOnlyConfig,
    FreeEnergyCollisionOnlyResult,
    FreeEnergyCollisionOnlyState,
    StaticDropletDiagnosticResult,
    central_gradient_3d,
    collision_then_adapter_stream,
    diagnose_static_droplet,
    estimate_droplet_radius,
    force_minus_phi_grad_mu,
    force_mu_grad_phi,
    initialize_free_energy_collision_only_state,
    initialize_static_droplet,
    laplacian_3d,
    periodic_chemical_potential_and_korteweg_force,
    phase_volume_smoothed,
    phase_volume_threshold,
    run_closed_periodic_free_energy_diagnostic,
    run_free_energy_adapter_stream_loop,
    run_free_energy_collision_only,
)
from .phasefield.ch_validation import free_energy_step_3d
from .phasefield.evolution_adapter import init_free_energy_g_3d
from .phasefield.stream_boundary_contract import (
    stream_d3q19_adapter,
    stream_free_energy_adapter,
)
from .pipeline_flow import (
    PipelineFlowConfig,
    make_pipeline_wall_mask,
    measure_strouhal,
    run_pipeline_flow,
)
from .planar_d3q19 import (
    collide_planar_cumulant_d3q19,
    lift_d2q9_to_d3q19,
    marginalize_d3q19_to_d2q9,
    maximum_planar_plane_spread,
)
from .population_positivity import (
    PositivityDiagnostics,
    limit_nonequilibrium_for_positivity,
)
from .porous_media import (
    CapillaryInvasionConfig,
    LaplaceTestConfig,
    PorousDrainageConfig,
    TwoPhasePoiseuilleConfig,
    apply_wall_wettability_sc,
    make_random_cylinder_medium,
    make_tube_array_medium,
    run_capillary_invasion,
    run_laplace_test,
    run_porous_drainage,
    run_two_phase_poiseuille,
)
from .porous_media3d import (
    PorousDrainageConfig3D,
    make_random_sphere_medium,
    make_tube_array_medium_3d,
    run_porous_drainage_3d,
)
from .postprocess import (
    RunningStats,
    compute_added_mass_2d,
    compute_added_mass_3d,
    compute_divergence,
    compute_drag_lift_coefficients,
    compute_enstrophy_2d,
    compute_kinetic_energy,
    compute_lambda2_criterion,
    compute_pressure_coefficient,
    compute_q_criterion,
    compute_recirculation_length,
    compute_strouhal_fft,
    compute_velocity_magnitude,
    compute_vorticity_2d,
    compute_vorticity_3d,
    extract_velocity_profile,
    extract_wake_profile,
)
from .powerlaw import (
    apply_body_force_shift,
    central_difference,
    collide_powerlaw_bgk,
    powerlaw_viscosity,
    strain_rate_shear_rate_2d,
    tau_from_viscosity,
    velocity_gradients_2d,
)
from .preprocess_geo import (
    compute_q_generic_3d,
    poly_to_mask_2d,
    poly_to_mask_and_q_2d,
    random_porosity_mask_2d,
    random_porosity_mask_3d,
    voxelize_stl_3d,
)
from .propeller_benchmark import (
    PropellerBenchmarkConfig,
    moving_wall_bounce_back_3d,
    rotating_wall_velocity_3d,
    run_propeller_benchmark,
)
from .propeller_cad import (
    GENERIC_PRESET,
    KP505_PRESET,
    PropellerGeometryConfig,
    build_propeller_mask,
    propeller_statistics,
)
from .propeller_ibm import (
    IBMPropellerConfig,
    run_ibm_propeller_benchmark,
)
from .protocols import BoundaryCondition, CollisionOperator
from .rans_common import (
    collide_rans_3d,
    collide_rans_bgk3d,
    collide_rans_bgk27,
    collide_rans_mrt3d,
    collide_rans_mrt27,
)
from .rans_ke import (
    KESolver,
    KOmegaSSTSolver,
    collide_rans_ke,
    collide_rans_komega_sst,
    komega_sst_collision_d2q9,
)
from .reporters import (
    CallbackReporter,
    EarlyStopReporter,
    FieldSampleReporter,
    Reporter,
    ReporterBase,
    StepContext,
    ThroughputReporter,
    dispatch,
)
from .resistance_component_audit import (
    ResistanceComponentAudit,
    audit_resistance_components,
)
from .rotating_cylinder import (
    RotatingCylinderConfig,
    moving_wall_bounce_back,
    rotating_wall_velocity,
    run_rotating_cylinder,
)
from .roughness import (
    apply_rough_wall_bounce_back,
    compute_rough_wall_slip_velocity,
    roughness_b_correction,
)
from .scan_runner import (
    EarlyStopSpec,
    PointOutcome,
    ScanExecutor,
    ScanPlan,
    ScanPoint,
    ScanVariable,
    assign_points_to_gpus,
    git_code_sha,
    open_catalog,
    run_scan_point,
    split_points,
)
from .ship_cad import (  # noqa: I001
    ShipHullType,
    export_hull_stl,
    generate_hull_body_plan,
    generate_hull_previews,
    generate_hull_sideprofile,
    generate_hull_waterplane,
    hull_block_coefficient,
    hull_statistics,
    kcs_hull_mask,
    series60_hull_mask,
    ship_lbm_parameters,
    ship_resistance_estimate,
    theoretical_block_coefficient,
)
from .ship_cad import (
    build_hull_mask as build_ship_hull_mask,
)
from .ship_cad3d import (
    CADGeometryEngine,
    TriangleMesh,
    create_parametric_hull_mesh,
    export_mesh_gltf,
    export_mesh_stl_ascii,
    import_mesh_stl,
)
from .ship_flow import ShipHullFlowConfig, run_ship_hull_flow
from .simulation import LBMSimulation
from .sloshing_tank import (
    SloshingTankConfig,
    faltinsen_natural_frequency,
    make_sloshing_wall_mask,
    run_sloshing_tank,
)
from .solver import collide_bgk, collide_mrt, collide_rlbm, collide_trt, correct_mass, stream
from .solver3d import (
    collide_bgk3d,
    collide_mrt3d,
    collide_rlbm3d,
    collide_trt3d,
    correct_mass3d,
    stream3d,
)
from .spalding_wall_model import (
    SpaldingWallDiagnostics,
    WallExchangeInterfaceClearance,
    WallExchangeSamples,
    apply_spalding_exchange_wall_model,
    assess_wall_exchange_interface_clearance,
    effective_bfl_wall_distance,
    sample_wall_exchange_velocity,
    solve_spalding_friction_velocity,
    spalding_u_plus_from_y_plus,
    spalding_y_plus,
)
from .spatial_convergence import (
    SpatialConvergenceAssessment,
    assess_spatial_convergence,
)
from .sphere_bfl_control_volume import (
    SphereBFLControlVolumeConfig,
    run_sphere_bfl_control_volume,
    schiller_naumann_cd,
)
from .sphere_boundary_factorial import assess_sphere_domain_inlet_factorial
from .sphere_boundary_sensitivity import assess_sphere_inlet_sponge_pair
from .sphere_domain_sensitivity import (
    assess_sphere_domain_convergence,
    assess_sphere_domain_sensitivity_pair,
)
from .sphere_flow import SphereFlowConfig, run_sphere_flow
from .sphere_water_entry import SphereWaterEntryConfig, run_sphere_water_entry
from .sponge_bc import (
    apply_target_sponge_2d,
    apply_target_sponge_3d,
    apply_viscous_sponge_2d,
    apply_viscous_sponge_3d,
    build_mean_equilibrium_2d,
    build_mean_equilibrium_3d,
    sponge_profile,
)
from .sponge_layer import (
    apply_equilibrium_difference_sponge,
    build_anisotropic_sponge_sigma_3d,
    build_sponge_sigma_3d,
    smoothstep5,
)
from .static_block_amr import (
    AMRAdvanceResult,
    NestedStaticBlockAMR3D,
    PopulationRefluxLedger,
    StaticBlockAMR3D,
    StaticBlockAMRConfig,
    convective_refined_tau,
)
from .streamlines import (
    Streamline,
    compute_residence_time_2d,
    seed_points_line_2d,
    seed_points_line_3d,
    seed_points_uniform_2d,
    seed_points_uniform_3d,
    streamlines_to_dict,
    trace_streamlines_2d,
    trace_streamlines_3d,
)
from .suboff_cad import (
    SuboffConfig,
    SuboffHullType,
    build_suboff_mask,
    export_suboff_stl,
    generate_suboff_previews,
    suboff_hull_mask,
    suboff_radius_profile,
    suboff_statistics,
)
from .suboff_nested_convergence import assess_suboff_nested_convergence
from .suboff_resistance import (
    SuboffResistanceBenchmarkConfig,
    run_suboff_resistance_benchmark,
)
from .suboff_static_amr import (
    SuboffGeometryResolution,
    SuboffNestedStaticAMRPlan,
    SuboffStaticAMRPlan,
    apply_suboff_appendage_halfway_links,
    assess_suboff_geometry_resolution,
    build_fine_suboff_mask,
    build_nested_fine_suboff_mask,
    plan_nested_suboff_static_amr,
    plan_suboff_static_amr,
)
from .surface_area_weights import (
    SurfaceAreaWeightDiagnostics,
    bfl_surface_area_weights,
)
from .surface_integrals import (
    area_average_2d,
    area_average_3d,
    force_coefficients,
    mass_flow_rate_2d,
    mass_flow_rate_3d,
    moment_coefficients,
    pressure_drop,
    surface_force_2d,
    surface_force_3d,
    surface_moment_2d,
    surface_moment_3d,
)
from .synthetic_inflow import (
    DFSEMInlet,
    DigitalFilterInlet,
    apply_dfsem_inlet_2d,
    apply_dfsem_inlet_3d,
)
from .thermal import (
    C_D2Q5,
    W_D2Q5,
    apply_buoyancy_force,
    collide_thermal_bgk,
    equilibrium_thermal,
    macroscopic_thermal,
    stream_thermal,
)
from .thermal3d import (
    C_D3Q7,
    W_D3Q7,
    ThermalCavity3DConfig,
    apply_buoyancy_force_3d,
    collide_thermal_bgk_3d,
    equilibrium_thermal_3d,
    macroscopic_thermal_3d,
    run_thermal_cavity_3d,
    stream_thermal_3d,
)
from .turbulence import (
    collide_dynamic_smagorinsky_bgk,
    collide_dynamic_smagorinsky_bgk3d,
    collide_smagorinsky_bgk,
    collide_smagorinsky_bgk3d,
    collide_smagorinsky_bgk27,
    collide_smagorinsky_mrt,
    collide_smagorinsky_mrt3d,
    collide_smagorinsky_mrt27,
    collide_vreman_bgk,
    collide_vreman_bgk3d,
    collide_vreman_bgk27,
    collide_vreman_mrt3d,
    collide_vreman_mrt27,
    collide_wale_bgk,
    collide_wale_bgk3d,
    collide_wale_bgk27,
    collide_wale_mrt3d,
    collide_wale_mrt27,
)
from .turbulence_capability_contract import (
    TurbulenceCapability,
    TurbulenceWithheldError,
    require_turbulence_capability,
    turbulence_capability_matrix,
    turbulence_hot_path_audit,
)
from .turbulence_stats import (
    TurbulenceStatsAccumulator,
    compute_reynolds_stresses,
    compute_turbulence_intensity,
    compute_turbulence_length_scale,
    turbulence_stats_from_checkpoints,
)
from .turbulent_channel import (
    TurbulentChannelConfig,
    log_law_velocity,
    run_turbulent_channel,
    viscous_sublayer_velocity,
)
from .unit_converter import LBMUnitConverter
from .utils import (
    DiagnosticPoint,
    configure_cpu_threads,
    flow_step_image_path,
    get_reproducibility_metadata,
    legacy_snapshot_image_path,
    prepare_run_dir,
    resolve_device,
    write_legacy_snapshot_alias,
)
from .vtk_export import (
    export_checkpoint_vtk,
    export_vtk_2d,
    export_vtk_3d,
)
from .wall_exchange_yplus import (
    WallExchangeYPlusAggregate,
    WallExchangeYPlusSummary,
    aggregate_wall_exchange_yplus_summaries,
    summarize_wall_exchange_yplus,
)
from .wall_function_admission import WallFunctionRunRequest, require_wall_function_run
from .wall_function_contract import (
    ValidationLevel,
    WallFunctionCapability,
    WallFunctionCompatibilityError,
)
from .wall_model import wall_function_3d, wall_function_d3q27
from .wall_refinement_combination_gate import (
    CollisionFamily as WallRefinementCollisionFamily,
)
from .wall_refinement_combination_gate import (
    CombinationEvidence,
    CombinationGateDecision,
    GeometryKind,
    GeometryOwnership,
    PhysicsModel,
    RefinementType,
    WallRefinementCombination,
    WallTreatment,
    assess_wall_refinement_combination,
)
from .wall_refinement_combination_gate import (
    GateStatus as WallRefinementGateStatus,
)
from .wall_refinement_combination_gate import (
    Lattice as WallRefinementLattice,
)
from .wave_bc import (
    airy_wave_velocity_3d,
    apply_jonswap_inlet_3d,
    apply_wave_inlet_3d,
    jonswap_spectrum,
    jonswap_wave_velocity_3d,
    zou_he_inlet_velocity_profile_3d,
)
from .yplus_guide import (
    DragMonitor,
    estimate_exchange_yplus,
    estimate_yplus,
    grid_quality_metrics,
    plan_exchange_yplus_refinement,
    recommend_grid,
    yplus_recommendation,
)

__all__ = [
    "__version__",
    # Adaptive mesh refinement (AMR)
    "AdaptationSchedule",
    "AMRPatch2D",
    "AMRPatch3D",
    "AdaptiveSolver2D",
    "AdaptiveSolver3D",
    "nonequilibrium_indicator_2d",
    "vorticity_indicator_2d",
    "gradient_indicator_2d",
    "nonequilibrium_indicator_3d",
    "vorticity_indicator_3d",
    "gradient_indicator_3d",
    "mark_cells_for_refinement",
    "damp_interface_nonequilibrium",
    "interface_shell_blend",
    "PopulationRefluxLedger",
    "AMRAdvanceResult",
    "NestedStaticBlockAMR3D",
    "StaticBlockAMR3D",
    "StaticBlockAMRConfig",
    "convective_refined_tau",
    "NaturalKBCCollisionExecutor",
    "collide_in_z_chunks",
    "AMRInterfaceValidationConfig",
    "run_amr_interface_validation",
    "SpatialConvergenceAssessment",
    "assess_spatial_convergence",
    "SuboffGeometryResolution",
    "SuboffNestedStaticAMRPlan",
    "SuboffStaticAMRPlan",
    "apply_suboff_appendage_halfway_links",
    "assess_suboff_geometry_resolution",
    "build_nested_fine_suboff_mask",
    "build_fine_suboff_mask",
    "plan_nested_suboff_static_amr",
    "plan_suboff_static_amr",
    "assess_suboff_nested_convergence",
    "InterfaceFilterControlVolumeClearance",
    "assess_interface_filter_control_volume_clearance",
    "ControlVolumeForceResult",
    "NestedControlVolumeAssessment",
    "assess_nested_control_volume_invariance",
    "box_control_volume",
    "fluid_momentum",
    "observe_control_volume_force",
    "streaming_momentum_import",
    "SpaldingWallDiagnostics",
    "WallExchangeInterfaceClearance",
    "WallExchangeSamples",
    "apply_spalding_exchange_wall_model",
    "assess_wall_exchange_interface_clearance",
    "effective_bfl_wall_distance",
    "sample_wall_exchange_velocity",
    "solve_spalding_friction_velocity",
    "spalding_u_plus_from_y_plus",
    "spalding_y_plus",
    "assess_sphere_domain_sensitivity_pair",
    "assess_sphere_domain_convergence",
    "ResistanceComponentAudit",
    "audit_resistance_components",
    "assess_sphere_inlet_sponge_pair",
    "assess_sphere_domain_inlet_factorial",
    "WallExchangeYPlusAggregate",
    "WallExchangeYPlusSummary",
    "aggregate_wall_exchange_yplus_summaries",
    "summarize_wall_exchange_yplus",
    "apply_equilibrium_difference_sponge",
    "build_anisotropic_sponge_sigma_3d",
    "build_sponge_sigma_3d",
    "smoothstep5",
    "PositivityDiagnostics",
    "limit_nonequilibrium_for_positivity",
    "SphereBFLControlVolumeConfig",
    "run_sphere_bfl_control_volume",
    "schiller_naumann_cd",
    "non_equilibrium_far_field_bc_3d",
    "CYLINDER_RE100_CD_REFERENCE",
    "CYLINDER_RE100_ST_REFERENCE",
    "CylinderBFLControlVolumeConfig",
    "estimate_strouhal_from_lift",
    "run_cylinder_bfl_control_volume",
    "FlatPlateWallModelConfig",
    "ittc_1957_friction_coefficient",
    "run_flat_plate_wall_model",
    "assess_flat_plate_convergence",
    "SurfaceAreaWeightDiagnostics",
    "bfl_surface_area_weights",
    "BFLWallPressureDiagnostics",
    "integrate_bfl_projected_pressure",
    "reconstruct_bfl_wall_pressure",
    # D2Q9 lattice
    "C",
    "W",
    "OPPOSITE",
    "equilibrium",
    "macroscopic",
    # 2D boundaries
    "cylinder_mask",
    "make_channel_wall_mask",
    "bounce_back_cells",
    "compute_obstacle_forces",
    "zou_he_inlet_velocity",
    "zou_he_outlet_pressure",
    "apply_simple_channel_boundaries",
    "apply_zou_he_channel_boundaries",
    # 2D solvers
    "collide_bgk",
    "collide_mrt",
    "collide_rlbm",
    "collide_trt",
    "stream",
    "correct_mass",
    # 2D runner
    "CylinderFlowConfig",
    "run_cylinder_flow",
    "compute_vorticity",
    # Rotating cylinder (Magnus effect)
    "RotatingCylinderConfig",
    "run_rotating_cylinder",
    "rotating_wall_velocity",
    "moving_wall_bounce_back",
    # Lid-driven cavity benchmark
    "LidDrivenCavityConfig",
    "run_lid_driven_cavity",
    "zou_he_moving_lid",
    "make_cavity_wall_mask",
    "compare_ghia",
    "GHIA_RE100",
    "GHIA_RE400",
    "GHIA_RE1000",
    # Backward-facing step benchmark
    "BackwardFacingStepConfig",
    "run_backward_facing_step",
    "make_bfs_solid_mask",
    "measure_reattachment_length",
    # Near-bed pipeline flow benchmark
    "PipelineFlowConfig",
    "run_pipeline_flow",
    "make_pipeline_wall_mask",
    "measure_strouhal",
    # Sloshing tank benchmark
    "SloshingTankConfig",
    "run_sloshing_tank",
    "make_sloshing_wall_mask",
    "faltinsen_natural_frequency",
    # Turbulent channel flow benchmark
    "TurbulentChannelConfig",
    "run_turbulent_channel",
    "log_law_velocity",
    "viscous_sublayer_velocity",
    # D3Q19 lattice
    "C3D",
    "W3D",
    "OPPOSITE3D",
    "equilibrium3d",
    "macroscopic3d",
    # 3D boundaries
    "sphere_mask",
    "make_channel_wall_mask_3d",
    "make_tank_wall_mask_3d",
    "bounce_back_cells_3d",
    "zou_he_inlet_velocity_3d",
    "zou_he_inlet_velocity_z",
    "zou_he_outlet_pressure_3d",
    "zou_he_outlet_pressure_z",
    "apply_simple_channel_boundaries_3d",
    "apply_zou_he_channel_boundaries_3d",
    "apply_water_entry_boundaries_3d",
    # 3D solvers
    "collide_bgk3d",
    "collide_mrt3d",
    "collide_rlbm3d",
    "collide_trt3d",
    "stream3d",
    "correct_mass3d",
    # 3D runners
    "SphereFlowConfig",
    "run_sphere_flow",
    # Single-phase sphere water entry (3D)
    "SphereWaterEntryConfig",
    "run_sphere_water_entry",
    "wigley_hull_mask",
    # Ellipsoid benchmark (prolate spheroid)
    "EllipsoidConfig",
    "build_ellipsoid_mask",
    "ellipsoid_statistics",
    "reference_ellipsoid_cd",
    "run_ellipsoid_benchmark",
    # Obstacle forces
    "compute_obstacle_forces_3d",
    "compute_obstacle_forces_27",
    "compute_obstacle_moments_3d",
    # Momentum exchange variants
    "momentum_exchange_standard",
    "momentum_exchange_galilean",
    "momentum_exchange_bfl",
    "momentum_exchange_stress",
    "momentum_exchange_pressure_friction",
    "compare_all_methods",
    # Turbulence
    "collide_smagorinsky_bgk",
    "collide_smagorinsky_mrt",
    "collide_smagorinsky_bgk3d",
    "collide_smagorinsky_mrt3d",
    # WALE turbulence
    "collide_wale_bgk",
    "collide_wale_bgk3d",
    "collide_wale_bgk27",
    # Vreman turbulence
    "collide_vreman_bgk",
    "collide_vreman_bgk3d",
    "collide_vreman_bgk27",
    # Wave BC
    "airy_wave_velocity_3d",
    "zou_he_inlet_velocity_profile_3d",
    "apply_wave_inlet_3d",
    # Marine / ship
    "ShipHullFlowConfig",
    "run_ship_hull_flow",
    # Ship CAD module
    "ShipHullType",
    "series60_hull_mask",
    "kcs_hull_mask",
    "hull_block_coefficient",
    "hull_statistics",
    "theoretical_block_coefficient",
    "generate_hull_body_plan",
    "generate_hull_waterplane",
    "generate_hull_sideprofile",
    "generate_hull_previews",
    "export_hull_stl",
    "build_ship_hull_mask",
    "ship_lbm_parameters",
    "ship_resistance_estimate",
    # SUBOFF submarine CAD module
    "SuboffHullType",
    "SuboffConfig",
    "suboff_radius_profile",
    "suboff_hull_mask",
    "build_suboff_mask",
    "suboff_statistics",
    "generate_suboff_previews",
    "export_suboff_stl",
    "SuboffResistanceBenchmarkConfig",
    "run_suboff_resistance_benchmark",
    # Propeller benchmark
    "PropellerGeometryConfig",
    "build_propeller_mask",
    "propeller_statistics",
    "configure_cpu_threads",
    "KP505_PRESET",
    "configure_cpu_threads",
    "GENERIC_PRESET",
    "PropellerBenchmarkConfig",
    "moving_wall_bounce_back_3d",
    "rotating_wall_velocity_3d",
    "run_propeller_benchmark",
    "CADGeometryEngine",
    "TriangleMesh",
    "create_parametric_hull_mesh",
    "import_mesh_stl",
    "export_mesh_stl_ascii",
    "export_mesh_gltf",
    # Multiphase models – D2Q9
    "psi_linear",
    "psi_exp",
    "psi_power",
    "sc_two_component_force",
    "collide_sc_two_component",
    "sc_single_component_force",
    "collide_sc_single_component",
    "color_gradient_step",
    "free_energy_step",
    "init_free_energy_g",
    # Multiphase models – D3Q19
    "sc_two_component_force_3d",
    "collide_sc_two_component_3d",
    "collide_sc_single_component_3d",
    "color_gradient_step_3d",
    "init_free_energy_g_3d",
    "free_energy_step_3d",
    # Multiphase models – D3Q27
    "sc_two_component_force_27",
    "collide_sc_two_component_27",
    "collide_sc_single_component_27",
    # Multiphase benchmark suite
    "StaticDropletConfig",
    "run_static_droplet",
    "FreeEnergyDropletConfig",
    "run_free_energy_droplet",
    "StaticDroplet3DConfig",
    "run_static_droplet_3d",
    "SpinodaleConfig",
    "run_spinodal_decomposition",
    "Spinodal3DConfig",
    "run_spinodal_decomposition_3d",
    "TwoPhaseChannelCompareConfig",
    "run_two_phase_channel_compare",
    "MultiphaseBenchmarkSuiteConfig",
    "run_multiphase_benchmark_suite",
    # Dam-break benchmark
    "DamBreakConfig",
    "run_dam_break",
    # Multiphase water-entry benchmark
    "MultiphaseWaterEntryConfig",
    "run_multiphase_water_entry",
    # Porous-media gas-water displacement benchmarks
    "make_random_cylinder_medium",
    "make_tube_array_medium",
    "apply_wall_wettability_sc",
    "LaplaceTestConfig",
    "run_laplace_test",
    "CapillaryInvasionConfig",
    "run_capillary_invasion",
    "TwoPhasePoiseuilleConfig",
    "run_two_phase_poiseuille",
    "PorousDrainageConfig",
    "run_porous_drainage",
    # 3D porous-media benchmarks
    "make_random_sphere_medium",
    "make_tube_array_medium_3d",
    "PorousDrainageConfig3D",
    "run_porous_drainage_3d",
    # Immersed Boundary Method (IBM)
    "ibm_delta_hat",
    "ibm_delta_4pt",
    "ibm_velocity_interpolate",
    "ibm_force_spread",
    "ibm_direct_forcing",
    "ibm_apply_body_force_2d",
    # Shared utilities
    "DiagnosticPoint",
    "resolve_device",
    "prepare_run_dir",
    "get_reproducibility_metadata",
    "flow_step_image_path",
    "legacy_snapshot_image_path",
    "write_legacy_snapshot_alias",
    "save_checkpoint",
    "load_checkpoint",
    "save_vtk",
    "save_vtk_binary",
    "save_vts",
    "save_hdf5",
    "save_xdmf",
    # VTK export (new)
    "export_vtk_2d",
    "export_vtk_3d",
    "export_checkpoint_vtk",
    # Aeroacoustics FWH (new)
    "AcousticObserver",
    "FWHSurface",
    "FWHResult",
    "compute_fwh_far_field",
    "compute_fwh_result",
    "compute_spl_spectrum",
    "extract_surface_pressure",
    "oaspl",
    # Conjugate heat transfer (new)
    "CHTConfig",
    "CHTState",
    "cht_solid_diffusion_step",
    "apply_cht_interface",
    "run_conjugate_ht_2d",
    "extract_velocity_profile",
    "extract_wake_profile",
    "compute_recirculation_length",
    "compute_pressure_coefficient",
    "compute_q_criterion",
    "compute_lambda2_criterion",
    "compute_vorticity_2d",
    "compute_vorticity_3d",
    "compute_velocity_magnitude",
    "compute_kinetic_energy",
    "compute_enstrophy_2d",
    "compute_divergence",
    "compute_drag_lift_coefficients",
    "compute_strouhal_fft",
    "compute_added_mass_2d",
    "compute_added_mass_3d",
    "RunningStats",
    "CollisionOperator",
    "BoundaryCondition",
    "load_config",
    "load_config_yaml",
    "save_config_json",
    "load_config_json",
    # D3Q27 lattice
    "C27",
    "W27",
    "OPPOSITE27",
    "equilibrium27",
    "macroscopic27",
    "collide_bgk27",
    "stream27",
    "correct_mass27",
    "collide_mrt27",
    "collide_smagorinsky_bgk27",
    "collide_smagorinsky_mrt27",
    # D3Q27 boundaries
    "bounce_back_cells_27",
    "zou_he_inlet_velocity_27",
    "zou_he_outlet_pressure_27",
    "make_channel_wall_mask_27",
    "apply_zou_he_channel_boundaries_27",
    "far_field_bc_27",
    # D3Q27 runner
    "SphereFlowD3Q27Config",
    "run_sphere_flow_d3q27",
    # Interpolated BC
    "bouzidi_bounce_back",
    "compute_q_circle",
    "bouzidi_bounce_back_3d",
    "compute_q_sphere",
    # Logging
    "logger",
    "configure_logging",
    # Minimal D2Q9 scaffold
    "D2Q9",
    "LBMSimulation",
    # Common timestep executor
    "LBMStepExecutor",
    # Reporter/callback protocol
    "Reporter",
    "ReporterBase",
    "StepContext",
    "dispatch",
    "CallbackReporter",
    "ThroughputReporter",
    "EarlyStopReporter",
    "FieldSampleReporter",
    # Parameter-sweep execution chain (DoE -> cases -> reporters -> catalog)
    "ScanPlan",
    "ScanExecutor",
    "ScanPoint",
    "ScanVariable",
    "EarlyStopSpec",
    "PointOutcome",
    "assign_points_to_gpus",
    "split_points",
    "run_scan_point",
    "open_catalog",
    "git_code_sha",
    # Pre-processing geometry
    "poly_to_mask_2d",
    "poly_to_mask_and_q_2d",
    "voxelize_stl_3d",
    "random_porosity_mask_2d",
    "random_porosity_mask_3d",
    "compute_q_generic_3d",
    # Unit converter
    "LBMUnitConverter",
    # Non-Newtonian (power-law) rheology
    "strain_rate_magnitude_2d",
    "apparent_viscosity_power_law",
    "collide_power_law_bgk",
    # Thermal LBM (D2Q9 + D2Q5 double-distribution)
    "C_D2Q5",
    "W_D2Q5",
    "equilibrium_thermal",
    "collide_thermal_bgk",
    "stream_thermal",
    "macroscopic_thermal",
    "apply_buoyancy_force",
    "C_D3Q7",
    "W_D3Q7",
    "ThermalCavity3DConfig",
    "equilibrium_thermal_3d",
    "collide_thermal_bgk_3d",
    "stream_thermal_3d",
    "macroscopic_thermal_3d",
    "apply_buoyancy_force_3d",
    "run_thermal_cavity_3d",
    # IBM 3D
    "ibm_velocity_interpolate_3d",
    "ibm_force_spread_3d",
    "ibm_direct_forcing_3d",
    "ibm_apply_body_force_3d",
    # Dynamic Smagorinsky
    "collide_dynamic_smagorinsky_bgk",
    "collide_dynamic_smagorinsky_bgk3d",
    # Wave BC additions
    "jonswap_spectrum",
    "jonswap_wave_velocity_3d",
    "apply_jonswap_inlet_3d",
    # Free-surface hull benchmark
    "HullFreeSurfaceConfig",
    "run_hull_free_surface",
    # Multi-backend dispatch
    "get_backend",
    "set_backend",
    # AI turbulence (HPC + AI demo)
    "EddyViscosityDataset",
    "EddyViscosityMLP",
    "LBMDatabase",
    "TrainConfig",
    "AIPipelineResult",
    "extract_les_samples_2d",
    "strain_rate_tensor_2d",
    "save_dataset_pt",
    "load_dataset_pt",
    "save_model",
    "load_model",
    "train_eddy_viscosity_model",
    "predict_nu_t_2d",
    "predict_tau_eff_2d",
    "collide_ai_les_bgk",
    "run_ai_dns_pipeline",
    "run_ai_les_pipeline",
    # Transformer-based self-supervised flow model
    "FlowTransformerArch",
    "FlowTransformerTrainConfig",
    "FlowFieldTransformer",
    "build_flow_token_batch",
    "train_flow_transformer_self_supervised",
    "save_flow_transformer_model",
    "load_flow_transformer_model",
    "reconstruct_flow_field",
    # Cumulant LBM
    "collide_cumulant_d2q9",
    "collide_cumulant_d3q19",
    "collide_cumulant_d3q27",
    "collide_cumulant_geier_d3q27",
    "collide_planar_cumulant_d3q19",
    "lift_d2q9_to_d3q19",
    "marginalize_d3q19_to_d2q9",
    "maximum_planar_plane_spread",
    # Streamline / pathline tracing
    "Streamline",
    "trace_streamlines_2d",
    "trace_streamlines_3d",
    "seed_points_uniform_2d",
    "seed_points_line_2d",
    "seed_points_uniform_3d",
    "seed_points_line_3d",
    "compute_residence_time_2d",
    "streamlines_to_dict",
    # Surface & volume integrals
    "mass_flow_rate_2d",
    "mass_flow_rate_3d",
    "area_average_2d",
    "area_average_3d",
    "surface_force_2d",
    "surface_force_3d",
    "surface_moment_2d",
    "surface_moment_3d",
    "pressure_drop",
    "force_coefficients",
    "moment_coefficients",
    # Turbulent inlet profiles
    "log_law_profile",
    "power_law_profile",
    "parabolic_profile",
    "blasius_profile",
    "womersley_profile",
    "synthetic_turbulence_2d",
    "apply_inlet_profile_2d",
    "apply_inlet_profile_3d",
    # Synthetic turbulent inflow (DFSEM + Digital Filter Method)
    "DFSEMInlet",
    "DigitalFilterInlet",
    "apply_dfsem_inlet_2d",
    "apply_dfsem_inlet_3d",
    # Wall roughness BC (equivalent sand-grain)
    "roughness_b_correction",
    "compute_rough_wall_slip_velocity",
    "apply_rough_wall_bounce_back",
    # Sponge / absorbing-layer outlet BC
    "sponge_profile",
    "apply_viscous_sponge_2d",
    "apply_viscous_sponge_3d",
    "apply_target_sponge_2d",
    "apply_target_sponge_3d",
    "build_mean_equilibrium_2d",
    "build_mean_equilibrium_3d",
    # Turbulence statistics (Reynolds stresses, TKE, Tu)
    "TurbulenceStatsAccumulator",
    "compute_reynolds_stresses",
    "compute_turbulence_intensity",
    "compute_turbulence_length_scale",
    "turbulence_stats_from_checkpoints",
    # Multi-GPU domain decomposition
    "DomainDecomposition",
    "MultiGPUSolver2D",
    "MultiGPUSolver3D",
    "MultiDeviceSolver3D",
    "halo_exchange_2d",
    "halo_exchange_3d",
    "auto_decompose",
    # Collision physical-property audit
    "CollisionViscosityAuditConfig",
    "run_collision_viscosity_audit",
    # Case registry (lettuce ExtFlow pattern) + integer-id BC registry (XLB)
    "CaseBase",
    "CaseUnits",
    "CaseRunResult",
    "ExportSpec",
    "get_case",
    "list_cases",
    "register_case",
    "run_case",
    "BC_ID_NONE",
    "BCKind",
    "BCPhase",
    "BoundaryCondition",
    "BoundaryConditionRegistry",
    "apply_boundary_conditions",
    "boundary_condition_registry",
    "build_bc_mask",
    "check_bc_consistency",
    "check_bc_overlaps",
    "derive_missing_mask",
    "LocalRefinementCapability",
    "LocalRefinementWithheldError",
    "REQUIRED_FRONTEND_METADATA",
    "local_refinement_capability_matrix",
    "require_local_refinement_capability",
    "BoundaryConditionCapability",
    "BoundaryConditionWithheldError",
    "boundary_capability_matrix",
    "require_boundary_condition_capability",
    "TurbulenceCapability",
    "TurbulenceWithheldError",
    "turbulence_capability_matrix",
    "require_turbulence_capability",
    "turbulence_hot_path_audit",
    "ValidationLevel",
    "WallFunctionCapability",
    "WallFunctionCompatibilityError",
    "WallFunctionRunRequest",
    "require_wall_function_run",
    "boundary_layer_indicator_2d",
    "boundary_layer_indicator_3d",
    "MAX_VR_LEVELS",
    "far_field_bc_3d",
    "wall_function_3d",
    "wall_function_d3q27",
    "collide_rlbm27",
    "collide_trt27",
    "stream27_roll",
    "free_surface_step_27",
    "init_fill_rectangular_27",
    "init_flags_from_fill_27",
    "init_mass_from_fill_27",
    "total_liquid_inventory_27",
    "CollisionCapability",
    "CollisionKernelWithheldError",
    "collide_advanced_3d",
    "collision_capability_matrix",
    "WallRefinementCollisionFamily",
    "CombinationEvidence",
    "CombinationGateDecision",
    "WallRefinementGateStatus",
    "GeometryKind",
    "GeometryOwnership",
    "WallRefinementLattice",
    "PhysicsModel",
    "RefinementType",
    "WallRefinementCombination",
    "WallTreatment",
    "assess_wall_refinement_combination",
    "AccuracyRecommendation",
    "ConvergenceEvidence",
    "ErrorMetric",
    "KPIDefinition",
    "PhysicalAccuracyEvidence",
    "recommend_by_physical_accuracy",
    "CompositionDecision",
    "CompositionRequest",
    "CompositionStatus",
    "SubContractResult",
    "SubContractStatus",
    "assess_composition",
    "compute_q_suboff",
    "AcousticsCapability",
    "AcousticsWithheldError",
    "PostProcessingAudit",
    "acoustics_capability_matrix",
    "acoustics_post_processing_audit",
    "require_acoustics_capability",
    "free_energy_step_3d_27",
    "init_free_energy_g_3d_27",
    "DoubleWellFreeEnergy",
    "FreeEnergyCHValidationConfig",
    "FreeEnergyCHDiagnosticResult",
    "FreeEnergyCollisionOnlyConfig",
    "FreeEnergyCollisionOnlyResult",
    "FreeEnergyCollisionOnlyState",
    "FreeEnergyAdapterStreamLoopConfig",
    "FreeEnergyAdapterStreamLoopResult",
    "StaticDropletDiagnosticResult",
    "central_gradient_3d",
    "collision_then_adapter_stream",
    "diagnose_static_droplet",
    "estimate_droplet_radius",
    "force_minus_phi_grad_mu",
    "force_mu_grad_phi",
    "initialize_free_energy_collision_only_state",
    "initialize_static_droplet",
    "laplacian_3d",
    "periodic_chemical_potential_and_korteweg_force",
    "phase_volume_smoothed",
    "phase_volume_threshold",
    "run_free_energy_adapter_stream_loop",
    "run_free_energy_collision_only",
    "run_closed_periodic_free_energy_diagnostic",
    "stream_d3q19_adapter",
    "stream_free_energy_adapter",
    "bubble_centroid_velocity_3d",
    "free_surface_vof_collide_3d",
    "free_surface_vof_step",
    "gravity_force_3d",
    "guo_force_delta_3d",
    "init_phi_bubble_3d",
    "init_phi_rayleigh_taylor_3d",
    "interface_compression_3d",
    "interface_normal_3d",
    "mean_curvature_3d",
    "mixing_layer_thickness_3d",
    "surface_tension_force_3d",
    "vof_advect_upwind_3d",
    "free_surface_step",
    "init_fill_rectangular",
    "init_flags_from_fill",
    "init_mass_from_fill",
    "total_liquid_inventory",
    "free_surface_step_2d",
    "init_fill_rectangular_2d",
    "CavitationConfig",
    "apply_cavitation_force",
    "psi_cavitation",
    "run_cavitation_flow",
    "schnerr_sauer_source",
    "apply_body_force_shift",
    "central_difference",
    "collide_powerlaw_bgk",
    "powerlaw_viscosity",
    "strain_rate_shear_rate_2d",
    "tau_from_viscosity",
    "velocity_gradients_2d",
    "collide_cascaded_d3q19",
    "collide_cascaded_d3q27",
    "collide_kbc_d3q19",
    "collide_kbc_d3q27",
    "collide_natural_kbc_d3q19",
    "discrete_entropy",
    "kbc_decompose_d3q19",
    "kbc_decompose_d3q27",
    "solve_gamma_entropy",
    "ActuatorDiskConfig",
    "apply_actuator_disk",
    "run_actuator_disk_benchmark",
    "AirfoilConfig",
    "naca4_surface",
    "build_airfoil_mask",
    "run_airfoil_benchmark",
    "reference_cl_cd",
    "IBMPropellerConfig",
    "run_ibm_propeller_benchmark",
    "KESolver",
    "KOmegaSSTSolver",
    "collide_rans_ke",
    "collide_rans_komega_sst",
    "komega_sst_collision_d2q9",
    "collide_rans_3d",
    "collide_rans_bgk27",
    "collide_rans_bgk3d",
    "collide_rans_mrt27",
    "collide_rans_mrt3d",
    "DGLBMConfig",
    "DGLBMSuboffConfig",
    "build_dg_hull_band_mask",
    "build_dg_shell_mask",
    "collide_dg_lbm",
    "dg_compute_velocity_gradients",
    "run_dg_lbm_sphere_flow",
    "run_dg_lbm_suboff_flow",
    "collide_bgk_dg",
    "dg_advect",
    "dg_lbm_rhs",
    "dg_lbm_step",
    "dg_rhs",
    "equilibrium_dg",
    "get_ops",
    "lobatto_nodes",
    "macroscopic_dg",
    "nodal_from_mean",
    "BandTopology",
    "build_band_topology",
    "dg_advect_band",
    "dg_lbm_step_band",
    "dg_rhs_band",
    "hybrid_advect",
    "hybrid_step",
    "write_back_exports",
    "collide_vreman_mrt3d",
    "collide_vreman_mrt27",
    "collide_wale_mrt3d",
    "collide_wale_mrt27",
    "collide_cumulant_smag_d3q27",
    "DragMonitor",
    "estimate_exchange_yplus",
    "estimate_yplus",
    "grid_quality_metrics",
    "plan_exchange_yplus_refinement",
    "recommend_grid",
    "yplus_recommendation",
    "BoundaryType",
    "CollisionModel",
    "GeneralSimConfig",
    "GeneralSimEngine",
    "GeometryConfig",
    "GeometrySource",
    "LatticeModel",
    "OutputConfig",
    "OutputFormat",
    "PhysicsConfig",
    "SolverConfig",
]
