"""2D dam-break benchmark using multiphase LBM.

Simulates a rectangular column of heavy fluid (water) surrounded by light
fluid (air) that collapses under gravity.  Four multiphase models are
supported via the *model* option:

* ``"sc"``  – Shan-Chen two-component (SCMC).  Uses moderate density ratio
  with a smooth tanh interface to maintain stability.
* ``"scmp"`` – Shan-Chen single-component liquid–gas pseudopotential.
  Spontaneous liquid/gas density contrast is generated by G < 0.
* ``"cg"``  – Color-Gradient (Latva-Kokko & Rothman 2005).  Recoloring step
  maintains sharp immiscible interfaces; recommended for best results.
* ``"fe"``  – Free-Energy binary-fluid (simplified Swift et al.).
  Thermodynamically consistent interface driven by chemical potential.

Benchmark diagnostic
---------------------
The leading edge (x-front) of the heavy phase is tracked every
``output_interval`` steps and compared with the analytical free-fall
prediction (Martin & Moyce 1952, linearised):

    X*(t*) ≈ 1 + t*  (one-dimensional approximation)

where the non-dimensional quantities are

    X* = x_f / L       (front position / initial column width)
    t* = t · √(2g / L) (dimensionless time)

Outputs
-------
* ``run_metadata.json`` – simulation config + diagnostics
* ``front_position.csv`` – step, t*, X* per interval
* ``snapshot_XXXXXX.png`` – density field snapshots

References
----------
Martin & Moyce (1952) Phil. Trans. R. Soc. A 244 312
"""
from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

import matplotlib
import torch

from .boundaries import bounce_back_cells
from .d2q9 import equilibrium, macroscopic
from .multiphase import (
    collide_sc_single_component,
    collide_sc_two_component,
    color_gradient_step,
    free_energy_step,
    init_free_energy_g,
    psi_exp,
)
from .solver import stream
from .utils import prepare_run_dir, resolve_device

matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

MultiphaseModel = Literal["sc", "scmp", "cg", "fe"]


@dataclass(frozen=True)
class DamBreakConfig:
    """Configuration for the 2D dam-break benchmark.

    Geometry
    --------
    The domain is ``(nx, ny)`` grid cells.  The dam (heavy-fluid column) occupies
    ``x ∈ [0, dam_width)`` and ``y ∈ [0, ny)``.  All four walls are no-slip
    (bounce-back).

    Physics
    -------
    Heavy-fluid initial density: ``rho_heavy``.
    Light-fluid initial density: ``rho_light``.
    SC coupling constant ``G`` drives phase separation (model-dependent sign).
    Gravity ``g`` (lattice units/step²) acts in the −y direction.

    Model-specific notes
    --------------------
    * ``"cg"``  : best stability; recommended for publication-quality results.
    * ``"sc"``  : moderate density ratio (≤ 4:1) for stability; G drives
                  repulsion between the two components.
    * ``"scmp"``: G < 0 drives liquid-gas self-separation; rho_heavy/rho_light
                  acts as the liquid/gas density target ratio.
    * ``"fe"``  : A=0.1, B=0.1, kappa=0.02 by default; interface from FE.
    """

    # Grid
    nx: int = 400
    ny: int = 200
    # Dam geometry: width in cells
    dam_width: int = 100
    # Multiphase model
    model: MultiphaseModel = "cg"
    # Fluid densities (interpretation is model-dependent)
    rho_heavy: float = 0.8
    rho_light: float = 0.4
    # Coupling constant (> 0 for SC, < 0 for SCMP, 0.04 for CG surface tension)
    G: float = 0.9
    # Relaxation time (viscosity: ν = cs²(τ − ½) = (τ − 0.5)/3)
    tau: float = 1.0
    # Gravity acceleration (lattice units)
    g: float = 5e-5
    # Time-stepping
    n_steps: int = 4000
    output_interval: int = 400
    # Output
    output_root: Path = Path("outputs")
    run_name: str | None = None
    device: str = "cpu"
    overwrite: bool = False

    def __post_init__(self) -> None:
        object.__setattr__(self, "output_root", Path(self.output_root))
        object.__setattr__(self, "device", self.device.lower())

    def validate(self) -> None:
        if self.nx < 16 or self.ny < 8:
            msg = "nx and ny must be at least 16 and 8"
            raise ValueError(msg)
        if self.dam_width <= 0 or self.dam_width >= self.nx:
            msg = "dam_width must be in (0, nx)"
            raise ValueError(msg)
        if self.rho_heavy <= self.rho_light:
            msg = "rho_heavy must exceed rho_light"
            raise ValueError(msg)
        if self.tau <= 0.5:
            msg = f"tau={self.tau} must be > 0.5"
            raise ValueError(msg)

    def resolved_run_name(self) -> str:
        if self.run_name:
            return self.run_name
        return (
            f"dam_{self.model}_nx{self.nx}_ny{self.ny}"
            f"_dw{self.dam_width}_G{self.G:.2f}_g{self.g:.0e}_steps{self.n_steps}"
        )


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def _wall_mask(ny: int, nx: int, device: torch.device) -> torch.Tensor:
    """All-wall mask (bounce-back on four sides of a closed box)."""
    mask = torch.zeros((ny, nx), dtype=torch.bool, device=device)
    mask[0, :] = True   # bottom
    mask[-1, :] = True  # top
    mask[:, 0] = True   # left
    mask[:, -1] = True  # right
    return mask


def _smooth_profile(nx: int, dam_width: int, width: float, device: torch.device) -> torch.Tensor:
    """Return a (1, nx) tanh profile: 1.0 inside dam, 0.0 outside."""
    x = torch.arange(nx, dtype=torch.float32, device=device)
    return 0.5 * (1.0 - torch.tanh((x - dam_width) / width)).unsqueeze(0)


def _init_cg(ny, nx, dam_width, rho_heavy, rho_light, device):
    """Colour-gradient initialisation: sharp red/blue split."""
    prof = _smooth_profile(nx, dam_width, 3.0, device).expand(ny, nx)
    frac = 0.05  # minority fraction
    rho_r = rho_heavy * prof + rho_heavy * frac * (1.0 - prof)
    rho_b = rho_light * frac * prof + rho_light * (1.0 - prof)
    zero = torch.zeros((ny, nx), device=device)
    return equilibrium(rho_r, zero, zero), equilibrium(rho_b, zero, zero)


def _init_sc(ny, nx, dam_width, rho_heavy, rho_light, device):
    """SC two-component initialisation with smooth interface."""
    prof = _smooth_profile(nx, dam_width, 4.0, device).expand(ny, nx)
    frac = 0.15  # minority fraction (larger = more stable for SC)
    rho2 = rho_heavy * prof + rho_heavy * frac * (1.0 - prof)
    rho1 = rho_light * frac * prof + rho_light * (1.0 - prof)
    zero = torch.zeros((ny, nx), device=device)
    return equilibrium(rho1, zero, zero), equilibrium(rho2, zero, zero)


def _init_scmp(ny, nx, dam_width, rho_heavy, rho_light, device):
    """SCMP single-component: liquid (rho_heavy) in dam, gas (rho_light) outside."""
    prof = _smooth_profile(nx, dam_width, 4.0, device).expand(ny, nx)
    rho0 = rho_heavy * prof + rho_light * (1.0 - prof)
    zero = torch.zeros((ny, nx), device=device)
    return equilibrium(rho0, zero, zero)


def _init_fe(ny, nx, dam_width, device):
    """Free-Energy initialisation: phi=+1 in dam, phi=-1 outside."""
    prof = _smooth_profile(nx, dam_width, 4.0, device).expand(ny, nx)
    phi = 2.0 * prof - 1.0  # +1 in dam, -1 outside
    rho = torch.ones((ny, nx), device=device)
    zero = torch.zeros((ny, nx), device=device)
    f = equilibrium(rho, zero, zero)
    g = init_free_energy_g(phi, zero, zero)
    return f, g


def _find_front_x(rho_heavy: torch.Tensor, rho_light: torch.Tensor,
                  wall: torch.Tensor, threshold: float = 0.45) -> float:
    """Return the x-position of the rightmost column where heavy phase dominates."""
    phi = rho_heavy / (rho_heavy + rho_light + 1e-12)
    # Average over interior y rows only
    phi_mean = phi[1:-1, :].mean(dim=0)  # (nx,)
    heavy_cols = (phi_mean > threshold).nonzero(as_tuple=True)[0]
    if heavy_cols.numel() == 0:
        return 0.0
    return float(heavy_cols.max().item())


def _save_snapshot(
    run_dir: Path, step: int,
    rho_heavy: torch.Tensor, rho_light: torch.Tensor,
    model: str,
) -> None:
    phi = (rho_heavy / (rho_heavy + rho_light + 1e-12)).detach().cpu().numpy()
    fig, ax = plt.subplots(figsize=(8, 4), constrained_layout=True)
    im = ax.imshow(phi, origin="lower", cmap="Blues", vmin=0, vmax=1)
    plt.colorbar(im, ax=ax, fraction=0.03, label="Heavy-fluid phase fraction φ")
    ax.set_title(f"Dam break ({model.upper()}) – step {step:d}")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    out = run_dir / f"snapshot_{step:06d}.png"
    fig.savefig(out, dpi=120)
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------------

def run_dam_break(config: DamBreakConfig) -> Path:
    """Run the dam-break benchmark and write diagnostics to *output_root*.

    Args:
        config: Simulation configuration.

    Returns:
        Path of the output directory created for this run.
    """
    config.validate()
    device = resolve_device(config.device)
    run_dir = prepare_run_dir(
        config.output_root, "dam_break", config.resolved_run_name(), config.overwrite
    )

    ny, nx = config.ny, config.nx
    L = float(config.dam_width)
    sqrt_coeff = (2.0 * config.g / L) ** 0.5 if config.g > 0 else 1.0

    wall = _wall_mask(ny, nx, device)

    # ----- initialise model state -----
    if config.model == "cg":
        f1, f2 = _init_cg(ny, nx, config.dam_width, config.rho_heavy, config.rho_light, device)
    elif config.model == "sc":
        f1, f2 = _init_sc(ny, nx, config.dam_width, config.rho_heavy, config.rho_light, device)
    elif config.model == "scmp":
        f_single = _init_scmp(ny, nx, config.dam_width, config.rho_heavy, config.rho_light, device)
    elif config.model == "fe":
        f_fe, g_fe = _init_fe(ny, nx, config.dam_width, device)
    else:
        msg = f"Unknown model: {config.model!r}"
        raise ValueError(msg)

    print(
        f"Running dam-break ({config.model.upper()})  "
        f"device={device}  NX={nx}  NY={ny}  "
        f"L={L:.0f}  G={config.G}  g={config.g:.1e}  steps={config.n_steps}"
    )
    print(f"Run directory: {run_dir}")

    diagnostics: list[dict[str, object]] = []
    front_series: list[tuple[int, float, float]] = []
    gy = -config.g  # downward gravity

    for step in range(1, config.n_steps + 1):
        # ----- collision + streaming -----
        if config.model == "cg":
            A_surface = config.G * 0.04
            # f1=red=heavy(water), f2=blue=light(air)
            f1, f2 = color_gradient_step(f1, f2, tau=config.tau, A=A_surface, gy=gy, solid_mask=wall)
            f1, f2 = stream(f1), stream(f2)
            f1 = bounce_back_cells(f1, wall)
            f2 = bounce_back_cells(f2, wall)
            rho_h = f1.sum(dim=0)  # RED = heavy (water)
            rho_l = f2.sum(dim=0)  # BLUE = light (air)

        elif config.model == "sc":
            f1, f2 = collide_sc_two_component(
                f1, f2, G_12=config.G, tau1=config.tau, tau2=config.tau,
                gy=gy, solid_mask=wall,
            )
            f1, f2 = stream(f1), stream(f2)
            f1 = bounce_back_cells(f1, wall)
            f2 = bounce_back_cells(f2, wall)
            rho_h = f2.sum(dim=0)  # component 2 = heavy
            rho_l = f1.sum(dim=0)  # component 1 = light

        elif config.model == "scmp":
            G_eff = -abs(config.G) * 1.5
            f_single = collide_sc_single_component(
                f_single, G=G_eff, tau=config.tau, psi_fn=psi_exp,
                gy=gy, solid_mask=wall,
            )
            f_single = stream(f_single)
            f_single = bounce_back_cells(f_single, wall)
            rho_all, _, _ = macroscopic(f_single)
            rho_h = rho_all
            rho_l = config.rho_heavy + config.rho_light - rho_all

        elif config.model == "fe":
            f_fe, g_fe = free_energy_step(
                f_fe, g_fe, tau_f=config.tau, gy=gy,
                A=0.1, B=0.1, kappa=0.02, Gamma=0.5,
                rho_heavy=config.rho_heavy, rho_light=config.rho_light,
            )
            f_fe, g_fe = stream(f_fe), stream(g_fe)
            f_fe = bounce_back_cells(f_fe, wall)
            g_fe = bounce_back_cells(g_fe, wall)
            phi_out = g_fe.sum(dim=0).clamp(-1.0, 1.0)
            # Map phi ∈ [−1,+1] → heavy/light densities
            alpha = (phi_out + 1.0) * 0.5  # ∈ [0,1], 1 = heavy phase
            rho_h = alpha * config.rho_heavy + (1.0 - alpha) * config.rho_light
            rho_l = (1.0 - alpha) * config.rho_heavy + alpha * config.rho_light

        # ----- diagnostics -----
        if step % config.output_interval == 0 or step == config.n_steps:
            x_front = _find_front_x(rho_h, rho_l, wall)
            X_star = x_front / L
            t_star = float(step) * sqrt_coeff
            front_series.append((step, t_star, X_star))

            mean_rho = float(rho_h[~wall].mean().item())
            diag: dict[str, object] = {
                "step": step,
                "t_star": round(t_star, 6),
                "X_star": round(X_star, 6),
                "mean_rho_heavy": round(mean_rho, 6),
            }
            diagnostics.append(diag)
            print(
                f"step={step:5d}  t*={t_star:.3f}  X*={X_star:.3f}  "
                f"mean_ρ={mean_rho:.4f}"
            )
            _save_snapshot(run_dir, step, rho_h, rho_l, config.model)

    # ----- write outputs -----
    front_csv = run_dir / "front_position.csv"
    with front_csv.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["step", "t_star", "X_star"])
        writer.writerows(front_series)

    metadata = {
        "config": {**asdict(config), "output_root": str(config.output_root)},
        "diagnostics": diagnostics,
        "note": (
            "X* = x_front / L,  t* = step * sqrt(2g/L).  "
            "Martin-Moyce (1952) analytical: X* ≈ 1 + t* for early times."
        ),
    }
    (run_dir / "run_metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"Saved metadata → {run_dir / 'run_metadata.json'}")
    return run_dir


__all__ = ["DamBreakConfig", "run_dam_break"]
