"""Pure paired-link liquid-mass reference ledger for D3Q19 free surfaces.

This module is diagnostic/reference code; it is intentionally not called by
``free_surface_step``.  It isolates the conservative account that a moving
LIQUID↔INTERFACE link requires when topology is held fixed.

For a pull-streamed population ``q`` at INTERFACE target ``x``, whose source
``s = x - c_q`` is LIQUID, define the *one* link transfer

``T_q(x) = f_post[q](s) - f_post[bar(q)](x)``.

The current solver's mass stencil adds ``T_q(x)`` to interface ``mass/fill``.
A closed conservative ledger must simultaneously add ``-T_q(x)`` to the bulk
inventory at the liquid source ``s``.  The latter cannot currently be applied
to the solver state without choosing a representation: LIQUID inventory is
represented by the LBM populations/density ``sum_q f``, while its independent
``mass`` field is initialized/clamped as a fixed ``rho_liquid`` per cell and
is not coupled to a per-link bulk debit.  Thus the solver lacks a distinct,
reconciled bulk-liquid inventory state (or an explicitly specified population
update) needed to enact this paired debit.  This helper reports the required
term but makes no solver correction.
"""
from __future__ import annotations

from dataclasses import dataclass

import torch

from .d3q19 import C, OPPOSITE
from .free_surface_lbm import INTERFACE, LIQUID


@dataclass(frozen=True)
class PairedLiquidInterfaceTransfer:
    """Per-cell conservative contributions generated by L/I pull links.

    ``transfer[q, x]`` is nonzero only for an INTERFACE target pulling from a
    LIQUID source.  ``interface_delta`` and ``bulk_delta`` are exact additive
    counterparts; their cellwise sum is therefore identically zero.
    """

    link_mask: torch.Tensor
    transfer: torch.Tensor
    interface_delta: torch.Tensor
    bulk_delta: torch.Tensor
    total_delta: torch.Tensor


def _pull_from_source(field: torch.Tensor) -> torch.Tensor:
    """Return D3Q19 values at ``x-c_q`` for scalar or population fields."""
    if field.ndim == 3:
        return torch.stack([
            field.roll((int(C[q, 2]), int(C[q, 1]), int(C[q, 0])), (0, 1, 2))
            for q in range(19)
        ])
    if field.ndim == 4 and field.shape[0] == 19:
        return torch.stack([
            field[q].roll((int(C[q, 2]), int(C[q, 1]), int(C[q, 0])), (0, 1, 2))
            for q in range(19)
        ])
    raise ValueError("field must have shape (nz, ny, nx) or (19, nz, ny, nx)")


def _source_flags(flags: torch.Tensor) -> torch.Tensor:
    return _pull_from_source(flags)


def paired_liquid_interface_transfers(
    f_post: torch.Tensor, flags: torch.Tensor,
) -> PairedLiquidInterfaceTransfer:
    """Build the frozen-topology LIQUID↔INTERFACE paired-link mass ledger.

    Args:
        f_post: Post-collision, pre-stream D3Q19 populations, shape
            ``(19, nz, ny, nx)``.
        flags: Topology flags at the same cell shape.

    Returns:
        A ledger with a single transfer per directed LIQUID→INTERFACE pull
        link, credited to its interface endpoint and debited at its liquid
        source endpoint. No topology, fill, mass, or population is mutated.
    """
    if f_post.ndim != 4 or f_post.shape[0] != 19:
        raise ValueError("f_post must have shape (19, nz, ny, nx)")
    if tuple(f_post.shape[1:]) != tuple(flags.shape):
        raise ValueError("flags shape must match f_post spatial dimensions")

    source_flags = _source_flags(flags)
    link_mask = (flags == INTERFACE).unsqueeze(0) & (source_flags == LIQUID)
    pulled = _pull_from_source(f_post)
    transfer = torch.where(link_mask, pulled - f_post[OPPOSITE.to(f_post.device)], torch.zeros_like(f_post))
    interface_delta = transfer.sum(dim=0)

    # Scatter each target-x contribution to source s=x-c_q.  For a tensor at
    # target x, ``roll(-c_q)`` has value target(x+c_q) at source x.
    bulk_delta = -torch.stack([
        transfer[q].roll((-int(C[q, 2]), -int(C[q, 1]), -int(C[q, 0])), (0, 1, 2))
        for q in range(19)
    ]).sum(dim=0)
    total_delta = interface_delta + bulk_delta
    return PairedLiquidInterfaceTransfer(
        link_mask=link_mask,
        transfer=transfer,
        interface_delta=interface_delta,
        bulk_delta=bulk_delta,
        total_delta=total_delta,
    )
