"""Prism-layer boundary mesh generator for DG-LBM coupled simulations.

Replaces the uniform Cartesian mesh near walls with body-fitted prism layers.
The prism cells follow the surface normal and use a coordinate mapping
(Jacobian + metric terms) so the DG solver can operate on body-fitted elements.
The far-field remains Cartesian and couples through the DG↔LBM band interface.

Key design decisions (matching Star-CCM+/OpenFOAM approach):
- Prism layers occupy < 5% of total cell count
- Layers are generated by advancing-layer normal marching
- First layer height is chosen to resolve y+ ~ 1
- Growth ratio controls layer thickness expansion
- DG on body-fitted elements requires Jacobian transform (implemented here)

References:
- Kallinderis & Ward (1993), "Prismatic grid generation for 3-D complex
  geometries", AIAA Journal.
- Hesthaven & Warburton (2008), "Nodal Discontinuous Galerkin Methods",
  Chapter 6 (curvilinear elements).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import torch

# Re-use the DG operators from the existing infrastructure
from .dg_advection import _Ops, lobatto_nodes, _lagrange_basis_matrices

# ---------------------------------------------------------------------------
# Prism layer data structures
# ---------------------------------------------------------------------------


@dataclass
class PrismLayerMesh:
    """Packed prism-layer mesh data for body-fitted DG.

    Attributes:
        n_surface: number of surface faces (one per solid-fluid interface cell).
        n_layers:  number of prism layers (typically 3–5).
        n_total_prism: total prism cells = n_surface × n_layers.
        ndim: 2 or 3.
        surface_centers: ``(n_surface, ndim)`` centres of surface interface cells
            (in grid-index space, float).
        surface_normals: ``(n_surface, ndim)`` unit outward normals (pointing
            INTO the fluid; marching direction is opposite of solid normal).
        layer_centers: ``(n_layers, n_surface, ndim)`` centres of each prism
            layer cell (layer 0 = closest to wall).
        layer_heights: ``(n_layers,)`` height (thickness) of each layer.
        jacobian: ``(n_layers, n_surface, ndim, ndim)`` Jacobian dx_i/dξ_j
            of the mapping from reference element [-1,1]^ndim to each prism cell.
            (Only populated for the wall-normal direction; transverse directions
             are treated as flat since prism layers don't curve tangentially.)
        inverse_jacobian: ``(n_layers, n_surface, ndim, ndim)`` for metric
            terms in the DG weak form.
        determinant: ``(n_layers, n_surface)`` |J| = det(jacobian).
        dg_ops: precomputed 1D DG operators for the wall-normal direction
            (the transverse directions use the standard Cartesian ops).
        cartesian_cells: set of ``(n_cart, ndim)`` Cartesian grid coordinates
            that remain in the LBM region (outside prism layers).
        band_indices: flat grid indices of prism layer cells (for indexing into
            a full-grid field to extract/insert values).
        band_mask: ``(*shape)`` boolean mask where True = prism layer cell.
    """

    n_surface: int
    n_layers: int
    ndim: int
    surface_centers: torch.Tensor  # (n_surface, ndim)
    surface_normals: torch.Tensor  # (n_surface, ndim)
    layer_centers: torch.Tensor  # (n_layers, n_surface, ndim)
    layer_heights: torch.Tensor  # (n_layers,)
    jacobian: Optional[torch.Tensor]  # (n_layers, n_surface, ndim, ndim)
    inverse_jacobian: Optional[torch.Tensor]
    determinant: Optional[torch.Tensor]
    dg_ops_wall_normal: _Ops  # 1D DG ops for wall-normal direction
    cartesian_cells: torch.Tensor  # (n_cart, ndim) kept in LBM
    band_indices: torch.Tensor  # (n_total_prism,) flat grid indices
    band_mask: torch.Tensor  # boolean, same shape as grid

    def to(self, device: torch.device) -> "PrismLayerMesh":
        """Move all tensors to *device*."""
        return PrismLayerMesh(
            n_surface=self.n_surface,
            n_layers=self.n_layers,
            ndim=self.ndim,
            surface_centers=self.surface_centers.to(device),
            surface_normals=self.surface_normals.to(device),
            layer_centers=self.layer_centers.to(device),
            layer_heights=self.layer_heights.to(device),
            jacobian=self.jacobian.to(device) if self.jacobian is not None else None,
            inverse_jacobian=self.inverse_jacobian.to(device)
            if self.inverse_jacobian is not None
            else None,
            determinant=self.determinant.to(device) if self.determinant is not None else None,
            dg_ops_wall_normal=self.dg_ops_wall_normal,
            cartesian_cells=self.cartesian_cells.to(device),
            band_indices=self.band_indices.to(device),
            band_mask=self.band_mask.to(device),
        )


# ---------------------------------------------------------------------------
# Surface normal extraction from solid mask
# ---------------------------------------------------------------------------


def extract_surface_normals(
    solid: torch.Tensor,
    *,
    smooth: bool = True,
    device: torch.device | None = None,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Extract surface cell centres and normals from a boolean solid mask.

    Finds all fluid cells adjacent to solid (6-connected) and computes the
    outward-facing normal (pointing from solid INTO fluid) at each interface.

    For 2-D masks ``(ny, nx)``, returns surface cells with 2 components.
    For 3-D masks ``(nz, ny, nx)``, returns 3 components.

    Args:
        solid: boolean mask ``(nz, ny, nx)`` or ``(ny, nx)``. True = solid.
        smooth: if True, apply a 1-iteration Gaussian smoothing to normals
            to reduce stair-step artefacts from the Cartesian mask.
        device: optional device to move result to (keeps same as input if None).

    Returns:
        ``(surface_coords, surface_normals, surface_flat_indices)`` where
        - surface_coords: ``(n_surface, ndim)`` float grid coordinates
        - surface_normals: ``(n_surface, ndim)`` unit outward normals
        - surface_flat_indices: ``(n_surface,)`` flat grid indices
    """
    if device is None:
        device = solid.device
    ndim = solid.ndim
    fluid = ~solid

    # Find fluid cells adjacent to solid in each direction
    near = torch.zeros_like(solid)
    if ndim == 3:
        axes_signs = [(2, 1), (2, -1), (1, 1), (1, -1), (0, 1), (0, -1)]
    else:  # ndim == 2
        axes_signs = [(1, 1), (1, -1), (0, 1), (0, -1)]

    for ax, sgn in axes_signs:
        near |= torch.roll(solid, sgn, dims=ax) & fluid

    # Coordinates and normals
    coords = torch.nonzero(near, as_tuple=False).to(torch.float32)  # (n_surf, ndim)
    n_surf = coords.shape[0]
    flat = torch.arange(solid.numel(), device=device).reshape(solid.shape)
    flat_idx = flat[near].to(device)

    normals = torch.zeros((n_surf, ndim), dtype=torch.float32, device=device)
    for k, (ax, sgn) in enumerate(axes_signs):
        # Fluid cell at (i,j,k) with solid at (i±1, j, k): normal points
        # from solid TOWARD fluid, so normal = -sgn along axis ax.
        shifted = torch.roll(solid, sgn, dims=ax) & fluid
        contrib = shifted[near]  # (n_surf,) bool
        if contrib.any():
            # The normal into fluid from solid: for sgn=+1, solid is at -ax
            # (since we rolled solid +ax and found it). Normal from solid
            # (at -ax) INTO fluid (at 0) points +ax.
            normals[contrib, ax] += float(sgn)

    # Normalise
    mag = normals.norm(dim=1, keepdim=True).clamp(min=1e-12)
    normals = normals / mag

    if smooth and n_surf > 0:
        # Simple Laplacian smooth on normals using k-nearest neighbours
        # in coordinate space (one iteration).
        diff = coords.unsqueeze(0) - coords.unsqueeze(1)  # (n, n, ndim)
        dist = diff.norm(dim=2)  # (n, n)
        neighbours = (dist < 2.0) & (dist > 0.0)  # 6-connected neighbours
        n_neigh = neighbours.sum(dim=1, keepdim=True).clamp(min=1).float()  # (n, 1)
        avg_n = (normals.unsqueeze(0) * neighbours.unsqueeze(-1).float()).sum(dim=1) / n_neigh
        normals = normals + 0.5 * avg_n
        mag = normals.norm(dim=1, keepdim=True).clamp(min=1e-12)
        normals = normals / mag

    return coords, normals, flat_idx


# ---------------------------------------------------------------------------
# Prism layer generation via advancing-layer normal marching
# ---------------------------------------------------------------------------


def generate_prism_layers(
    solid: torch.Tensor,
    n_layers: int = 5,
    first_height: float = 0.01,
    growth: float = 1.2,
    *,
    device: torch.device | None = None,
    degree: int = 1,
) -> PrismLayerMesh:
    """Generate body-fitted prism layers from a solid mask.

    For each solid-fluid interface cell, march outward along the surface normal
    to create *n_layers* prism cells. Layer heights grow geometrically:
    ``h_k = first_height · growth^k``.

    This is the primary entry point for the prism-layer generator.

    Args:
        solid: boolean solid mask ``(nz, ny, nx)`` or ``(ny, nx)``.
        n_layers: number of prism layers (default 5).
        first_height: height of the first (wall-adjacent) layer in grid units
            (default 0.01).  Should target y+ ≈ 1 for the given Re.
        growth: geometric growth ratio between consecutive layers (default 1.2).
        device: optional device (default: same as *solid*).
        degree: polynomial degree for the DG element (default 1 = P1 linear).

    Returns:
        :class:`PrismLayerMesh` with all data needed for body-fitted DG.

    Example::

        solid = sphere_mask(120, 80, 80, 30, 40, 40, 20, device="cpu")
        prism = generate_prism_layers(solid, n_layers=5, first_height=0.01, growth=1.2)

        # Access layer data
        print(f"Prism cells: {prism.n_total_prism}")
        print(f"LBM Cartesian cells remaining: {prism.cartesian_cells.shape[0]}")
        print(f"Layer heights: {prism.layer_heights}")
    """
    if device is None:
        device = solid.device
    solid = solid.to(device)

    ndim = solid.ndim
    shape = tuple(solid.shape)

    # 1. Extract surface cells and normals
    surf_coords, surf_normals, surf_flat = extract_surface_normals(
        solid, smooth=True, device=device
    )
    n_surface = surf_coords.shape[0]

    if n_surface == 0:
        raise ValueError("No fluid-solid interface found. Check solid mask.")

    # 2. Compute layer heights (geometric progression)
    heights = torch.tensor(
        [first_height * (growth**k) for k in range(n_layers)], dtype=torch.float32, device=device
    )  # (n_layers,)

    # 3. March outward from surface to generate layer centres
    # layer_centers[k, i, :] = surf_coords[i] + normal[i] * cumulative_offset[k]
    cum_offsets = torch.cumsum(heights, dim=0)  # (n_layers,)
    # Mid-cell positions: offset from surface
    mid_offsets = cum_offsets - heights / 2.0  # (n_layers,)

    layer_centers = (
        surf_coords.unsqueeze(0)  # (1, n_surf, ndim)
        + surf_normals.unsqueeze(0) * mid_offsets.unsqueeze(-1).unsqueeze(-1)
    )
    # shape: (n_layers, n_surface, ndim)

    # 4. Build the Cartesian-lattice mask: cells covered by prism layers
    n_total_prism = n_layers * n_surface

    # Mark all prism-covered cells: we snap layer centres to the nearest
    # grid cell and mark them as "prism band" (removed from LBM).
    band_mask = torch.zeros(shape, dtype=torch.bool, device=device)

    # Snap each layer centre to nearest integer grid cell and mark it
    layer_centers_int = layer_centers.round().long()  # (n_layers, n_surf, ndim)
    # Clamp to domain bounds
    for d in range(ndim):
        layer_centers_int[..., d] = layer_centers_int[..., d].clamp(0, shape[d] - 1)

    # Mark grid cells
    for k in range(n_layers):
        idx = tuple(layer_centers_int[k, :, d] for d in range(ndim))
        band_mask[idx] = True

    # Also mark the fluid surface cells themselves (first layer interface)
    surf_int = surf_coords.round().long()
    shape_t = torch.tensor(shape, device=device)
    for d in range(ndim):
        surf_int[:, d] = surf_int[:, d].clamp(0, shape_t[d].item() - 1)
    idx_surf = tuple(surf_int[:, d] for d in range(ndim))
    band_mask[idx_surf] = True

    # Don't include solid cells in the band
    band_mask = band_mask & ~solid

    # 5. Flat indices for band (prism layer cells)
    flat_grid = torch.arange(band_mask.numel(), device=device).reshape(shape)
    band_indices = flat_grid[band_mask]  # (n_band,)

    # Cartesian cells that stay in LBM
    cart_mask = ~band_mask & ~solid
    cart_coords = torch.nonzero(cart_mask, as_tuple=False).float()  # (n_cart, ndim)

    # 6. Compute Jacobian for wall-normal direction
    # Each prism cell maps from reference [-1,1]^ndim to physical space.
    # The wall-normal direction (ξ_n) maps [−1,1] → [0, h_k] along surface normal.
    # Transverse directions (ξ_1, ξ_2) stay Cartesian (dy=1, dx=1) for flat prisms.
    #
    # Jacobian dx_i/dξ_j: diagonal for flat prisms
    #   dx/dξ_wall = h_k/2 (wall-normal)
    #   dx/dξ_trans = 1/2  (transverse = cell width / reference width of 2)
    jac = torch.zeros((n_layers, n_surface, ndim, ndim), dtype=torch.float32, device=device)
    for k in range(n_layers):
        # Wall-normal direction: last axis maps [-1,1] → [0, h_k]
        jac[k, :, -1, -1] = heights[k] / 2.0
        # Transverse directions are 1 cell wide
        for d in range(ndim - 1):
            jac[k, :, d, d] = 0.5

    # Inverse Jacobian
    jac_inv = torch.zeros_like(jac)
    det = torch.zeros((n_layers, n_surface), dtype=torch.float32, device=device)
    for k in range(n_layers):
        for i in range(n_surface):
            jac_ki = jac[k, i]
            det_ki = torch.det(jac_ki)
            if abs(det_ki.item()) > 1e-15:
                det[k, i] = det_ki
                jac_inv[k, i] = torch.inverse(jac_ki)

    # 7. Precompute 1D DG operators for the wall-normal direction
    # The wall-normal element has length = first_height (worst case).
    # We use the minimum layer height to be conservative on CFL.
    min_dx = first_height
    from .dg_advection import get_ops as _get_dg_ops

    dg_ops_wn = _get_dg_ops(degree, float(min_dx), dtype=torch.float32, device=str(device))

    return PrismLayerMesh(
        n_surface=n_surface,
        n_layers=n_layers,
        ndim=ndim,
        surface_centers=surf_coords,
        surface_normals=surf_normals,
        layer_centers=layer_centers,
        layer_heights=heights,
        jacobian=jac,
        inverse_jacobian=jac_inv,
        determinant=det,
        dg_ops_wall_normal=dg_ops_wn,
        cartesian_cells=cart_coords,
        band_indices=band_indices,
        band_mask=band_mask,
    )


# ---------------------------------------------------------------------------
# DG body-fitted solver: uses Jacobian to transform reference operators
# ---------------------------------------------------------------------------


def dg_rhs_body_fitted(
    f_dg: torch.Tensor,
    velocities: torch.Tensor,
    ops_cart: _Ops,  # Cartesian DG ops (for transverse dirs)
    ops_wall: _Ops,  # DG ops for wall-normal direction
    prism: PrismLayerMesh,
    ext_field: torch.Tensor | None = None,
    opposite: torch.Tensor | None = None,
) -> torch.Tensor:
    """Semi-discrete RHS for DG advection on body-fitted prism elements.

    The prism elements are mapped from the reference cube [-1,1]^ndim via the
    Jacobian stored in *prism*.  The DG weak form on a mapped element uses
    metric terms (inverse Jacobian) to transform the gradient operator.

    **Current implementation**: For prism layers where each cell maps to a
    single grid cell (layer heights < 1 grid unit), the body-fitted correction
    applies a metric scaling to the wall-normal direction only.  Transverse
    directions use the standard Cartesian DG operators.

    Args:
        f_dg: nodal DOFs ``(Q, n_band, *node_axes)`` with node axes
            in ``(z, y, x)`` order with wall-normal axis LAST.
        velocities: ``(Q, ndim)`` lattice velocities.
        ops_cart: Cartesian DG ops for transverse directions.
        ops_wall: DG ops for wall-normal direction.
        prism: prism layer mesh (provides Jacobian, normals, etc.).
        ext_field: ``(Q, Ncell)`` exterior P0 values or None.
        opposite: ``(Q,)`` opposite-direction index map (for solid walls).

    Returns:
        ``df/dt`` with same shape as *f_dg*.
    """
    ndim = prism.ndim
    n_dims = f_dg.ndim

    rhs = torch.zeros_like(f_dg)

    for v in range(ndim):  # v=0:x, 1:y, 2:z
        c_axis = velocities[:, v].to(f_dg.dtype)
        if c_axis.abs().max().item() == 0.0:
            continue
        node_axis = n_dims - 1 - v  # px (last), py, pz

        nonzero = c_axis.abs() > 0.0
        sub = f_dg[nonzero]
        c_sub = c_axis[nonzero]

        # Choose Cartesian or body-fitted ops
        is_wall_normal = node_axis == n_dims - 1  # last node axis = wall-normal
        ax = ops_wall.Ax if is_wall_normal else ops_cart.Ax
        fl = ops_wall.face_lift if is_wall_normal else ops_cart.face_lift
        n_node = ops_wall.n_node if is_wall_normal else ops_cart.n_node
        p_last = n_node - 1

        # --- Volume term ---
        letters = "abcdefghijklmnopqrst"
        in_subs = [letters[i] for i in range(sub.ndim)]
        out_subs = list(in_subs)
        in_subs[node_axis] = "u"
        out_subs[node_axis] = "v"
        ein = f"vu,{''.join(in_subs)}->{''.join(out_subs)}"
        vol = torch.einsum(ein, ax, sub)

        # Apply metric scaling for wall-normal direction
        # For layers thinner than 1 grid unit, use 1/dx scaling
        if is_wall_normal:
            # Average layer height for metric scaling
            h_avg = prism.layer_heights.mean().item()
            vol = vol * (2.0 / max(h_avg, 1e-6))  # 2/dx from reference [-1,1]
        else:
            vol = vol * 2.0  # 1/dx = 2.0 for dx=0.5

        # --- Surface term ---
        inner_left = sub.select(node_axis, 0)
        inner_right = sub.select(node_axis, p_last)
        left_ext = torch.roll(inner_right, shifts=1, dims=1)  # neighbour's far node
        right_ext = torch.roll(inner_left, shifts=-1, dims=1)  # neighbour's near node

        pos = c_sub.view([c_sub.shape[0]] + [1] * (inner_left.ndim - 1)) > 0.0
        uL = torch.where(pos, left_ext, inner_left)
        uR = torch.where(pos, inner_right, right_ext)

        fl_l = fl[:, 0]
        fl_r = fl[:, 1]
        shape_fl = [1] * sub.ndim
        shape_fl[node_axis] = n_node
        surf = fl_l.view(shape_fl) * uL.unsqueeze(node_axis) + fl_r.view(shape_fl) * uR.unsqueeze(
            node_axis
        )

        c_view = c_sub.view([c_sub.shape[0]] + [1] * (sub.ndim - 1))
        rhs_sub = c_view * vol - c_view * surf
        rhs[nonzero] = rhs[nonzero] + rhs_sub

    return rhs


# ---------------------------------------------------------------------------
# Coupling: inject prism-layer cell-means into the Cartesian LBM field
# ---------------------------------------------------------------------------


def project_prism_to_cartesian(
    f_lbm: torch.Tensor,
    f_prism: torch.Tensor,
    prism: PrismLayerMesh,
) -> torch.Tensor:
    """Project prism-layer cell-mean values back into the Cartesian LBM field.

    The Cartesian cells covered by prism layers are "holes" in *f_lbm*.
    This fills them with the cell-mean of the surrounding prism cells so that
    standard LBM operations (stream, collide) can run on the full grid without
    holes.

    Args:
        f_lbm: ``(Q, *shape)`` Cartesian distribution.
        f_prism: ``(Q, n_prism_cells, *node_axes)`` prism DOFs.
        prism: prism layer mesh (provides band_mask for indexing).

    Returns:
        Updated *f_lbm* with prism locations filled.
    """
    node_axes = tuple(range(2, f_prism.ndim))
    mean = f_prism.mean(dim=node_axes)  # (Q, n_prism)
    f_lbm = f_lbm.clone()
    idx = torch.nonzero(prism.band_mask, as_tuple=True)
    f_lbm[(slice(None),) + idx] = mean
    return f_lbm


# ---------------------------------------------------------------------------
# Summary statistics
# ---------------------------------------------------------------------------


def prism_statistics(prism: PrismLayerMesh, solid: torch.Tensor) -> dict:
    """Return summary statistics for the prism layer mesh."""
    n_total = solid.numel()
    n_solid = int(solid.sum().item())
    n_prism = prism.band_indices.shape[0]
    n_cart = prism.cartesian_cells.shape[0]
    n_fluid = n_total - n_solid
    return {
        "total_cells": n_total,
        "solid_cells": n_solid,
        "prism_cells": n_prism,
        "cartesian_cells": n_cart,
        "prism_fraction_pct": n_prism / n_fluid * 100 if n_fluid > 0 else 0.0,
        "surface_faces": prism.n_surface,
        "n_layers": prism.n_layers,
        "layer_heights": prism.layer_heights.tolist(),
        "first_layer_height": float(prism.layer_heights[0].item()),
        "total_prism_thickness": float(prism.layer_heights.sum().item()),
    }


__all__ = [
    "PrismLayerMesh",
    "extract_surface_normals",
    "generate_prism_layers",
    "dg_rhs_body_fitted",
    "project_prism_to_cartesian",
    "prism_statistics",
]
