"""Prism-layer velocity correction for LBM.

Instead of an empirical wall-function body force, we resolve the viscous
sublayer analytically (u+ = y+ valid for y+ < 5) on body-fitted prism cells.

The prism layers are generated by marching outward along surface normals.
At each prism cell centre, the velocity is computed from the exact laminar
profile, then injected back into LBM by replacing the near-wall velocity.

No NS solve, no Newton iteration — just the exact viscous solution.
"""

import torch
import math
import time
from dataclasses import dataclass
from typing import Optional


# ── Surface extraction ──
def _surface_cells(solid: torch.Tensor) -> tuple:
    """Return (centres, normals, flat_idx) for fluid cells adjacent to solid."""
    fluid = ~solid
    near = torch.zeros_like(solid)
    for ax, sgn in [(0, 1), (0, -1), (1, 1), (1, -1), (2, 1), (2, -1)]:
        near |= torch.roll(solid, sgn, dims=ax) & fluid
    idx = torch.nonzero(near, as_tuple=False)
    centres = idx.float()
    normals = torch.zeros(idx.shape[0], 3)
    nz, ny, nx = solid.shape
    for i, (k, j, ii) in enumerate(idx):
        n = torch.zeros(3)
        for ax, sgn in [(0, -1), (0, 1), (1, -1), (1, 1), (2, -1), (2, 1)]:
            kk = k + sgn if ax == 0 else k
            jj = j + sgn if ax == 1 else j
            ii2 = ii + sgn if ax == 2 else ii
            if 0 <= kk < nz and 0 <= jj < ny and 0 <= ii2 < nx and solid[kk, jj, ii2]:
                n[ax] += float(-sgn)
        norm = n.norm()
        normals[i] = n / norm if norm > 0.5 else torch.tensor([1.0, 0.0, 0.0])
    flat_idx = idx[:, 0] * ny * nx + idx[:, 1] * nx + idx[:, 2]
    return centres, normals, flat_idx.long()


# ── Prism layer builder ──
def build_prism(
    solid: torch.Tensor, n_layers: int = 5, first_height: float = 0.02, growth: float = 1.15
) -> dict:
    """Build prism layers outward from the solid surface.

    Returns:
        centres:       (n_layers, N, 3) — cell centre coordinates
        heights:       (n_layers,)      — cell heights
        n_surface:     int
        surface_xyz:   (N, 3)           — surface fluid cell centres
        surface_norm:  (N, 3)           — unit outward normals
    """
    c0, n0, _ = _surface_cells(solid)
    N = c0.shape[0]
    h = torch.zeros(n_layers)
    h[0] = first_height
    for k in range(1, n_layers):
        h[k] = h[k - 1] * growth
    layer_c = torch.zeros(n_layers, N, 3)
    cum = 0.0
    for k in range(n_layers):
        cum += h[k] / 2.0
        layer_c[k] = c0 + cum * n0
        cum += h[k] / 2.0
    return {"centres": layer_c, "heights": h, "n_surface": N, "surface_xyz": c0, "surface_norm": n0}


# ── Runtime prism correction ──
class PrismCorrector:
    """Compute prism velocity from LBM u_tau and inject back."""

    def __init__(self, prism: dict, nu: float, device: torch.device):
        self.prism = {
            k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in prism.items()
        }
        self.nu = nu
        self.device = device
        self.N = prism["n_surface"]
        self.n_layers = len(prism["heights"])

    def correct_velocity(
        self, ux: torch.Tensor, uy: torch.Tensor, uz: torch.Tensor, u_tau: torch.Tensor
    ) -> tuple:
        """Return (ux_corr, uy_corr, uz_corr) with prism-resolved wall velocity."""
        nz, ny, nx = ux.shape
        c0 = self.prism["surface_xyz"]
        h = self.prism["heights"]
        nu = self.nu
        N = self.N

        ux_c = ux.clone()
        uy_c = uy.clone()
        uz_c = uz.clone()

        # Cache the cumulative heights
        cum_h = torch.zeros(self.n_layers, device=self.device)
        cum_h[0] = h[0] / 2.0
        for k in range(1, self.n_layers):
            cum_h[k] = cum_h[k - 1] + (h[k - 1] + h[k]) / 2.0

        for i in range(N):
            cx, cy, cz = int(c0[i, 0]), int(c0[i, 1]), int(c0[i, 2])
            if not (0 <= cx < nx and 0 <= cy < ny and 0 <= cz < nz):
                continue
            ut = u_tau[cz, cy, cx].item()
            if ut < 1e-12:
                continue

            # Interface velocity from viscous profile:
            # y_interface = cumulative height of last layer
            # y+ = y * ut / nu
            # u = ut * y+ = ut² * y / nu
            y_iface = cum_h[-1].item() + h[-1].item() / 2.0
            yp = y_iface * ut / nu
            if yp < 5.0:
                u_mag = ut * yp  # viscous sublayer
            else:
                u_mag = ut * (math.log(max(yp, 1.1)) / 0.41 + 5.0)  # log-law fallback

            # Project interface velocity onto Cartesian components
            # Use the bulk flow direction (streamwise = x by convention)
            ux_c[cz, cy, cx] = u_mag
            uy_c[cz, cy, cx] = 0.0  # wall-normal component goes to 0 at wall
            uz_c[cz, cy, cx] = 0.0

        return ux_c, uy_c, uz_c

    def inject_to_lbm(
        self, f: torch.Tensor, ux_c: torch.Tensor, uy_c: torch.Tensor, uz_c: torch.Tensor
    ):
        """Vectorized: rebuild equilibrium at all surface cells at once."""
        from .d3q19 import equilibrium3d

        c0 = self.prism["surface_xyz"]
        N = self.N

        # Gather corrected velocity at surface cells
        cz_all = c0[:, 2].long().clamp(0, f.shape[1] - 1)
        cy_all = c0[:, 1].long().clamp(0, f.shape[2] - 1)
        cx_all = c0[:, 0].long().clamp(0, f.shape[3] - 1)

        ux_surf = ux_c[cz_all, cy_all, cx_all]  # (N,)
        uy_surf = uy_c[cz_all, cy_all, cx_all]
        uz_surf = uz_c[cz_all, cy_all, cx_all]
        rho_surf = f[:, cz_all, cy_all, cx_all].sum(dim=0)  # (N,) — sum over pops

        # Reconstruct equilibrium for each surface cell
        # equilibrium3d expects (nz, ny, nx) tensors — only set non-zero at surface
        rho_t = torch.ones(f.shape[1], f.shape[2], f.shape[3], device=f.device)
        ux_t = torch.zeros_like(rho_t)
        uy_t = torch.zeros_like(rho_t)
        uz_t = torch.zeros_like(rho_t)

        rho_t[cz_all, cy_all, cx_all] = rho_surf
        ux_t[cz_all, cy_all, cx_all] = ux_surf
        uy_t[cz_all, cy_all, cx_all] = uy_surf
        uz_t[cz_all, cy_all, cx_all] = uz_surf

        feq = equilibrium3d(rho_t, ux_t, uy_t, uz_t)  # (19, nz, ny, nx)
        # Only overwrite surface cells
        mask = torch.zeros_like(rho_t, dtype=torch.bool)
        mask[cz_all, cy_all, cx_all] = True
        for q in range(19):
            f[q] = torch.where(mask, feq[q], f[q])


# ── Test ──
if __name__ == "__main__":
    import sys

    dev = sys.argv[1] if len(sys.argv) > 1 else "cpu"
    print(f"Prism layer test on {dev}")

    # Build cylinder
    nx, ny, nz, D = 100, 40, 4, 20
    solid = torch.zeros(nz, ny, nx, dtype=torch.bool)
    cy, cz = ny / 2, nz / 2
    for i in range(nx):
        for j in range(ny):
            for k in range(nz):
                if (j - cy) ** 2 + (k - cz) ** 2 < (D / 2) ** 2:
                    solid[k, j, i] = True

    prism = build_prism(solid, n_layers=3)
    print(f"Prism: {prism['n_surface']} surfaces × {len(prism['heights'])} layers")

    u_in, re, Df = 0.08, 200, float(D)
    nu = u_in * Df / re
    corr = PrismCorrector(prism, nu, torch.device(dev))

    # Test with random velocity field
    ux = torch.rand(nz, ny, nx) * u_in
    uy = torch.rand(nz, ny, nx) * 0.01
    uz = torch.zeros(nz, ny, nx)
    ut = torch.rand(nz, ny, nx) * 0.01

    if dev.startswith("sdaa"):
        import torch as _t

        _t.sdaa.set_device(int(dev.split(":")[1]))
        ux, uy, uz, ut, solid = [t.to(dev) for t in [ux, uy, uz, ut, solid]]

    ux_c, uy_c, uz_c = corr.correct_velocity(ux, uy, uz, ut)
    print(f"Velocity correction range: ux [{ux_c.min():.4f}, {ux_c.max():.4f}]")
    print("Prism corrector: PASSED")
